### ISSUE TITLE
Compatibility with Google Sheets?

### ISSUE THREAD

**Issue by pabloide86** [justkawal/excel#103]
Hi,
Is this library compatible with Google Sheets format by any chance? 
I can open the file with LibreOffice Calc without issues, but when I upload the xlsx file to Drive and I open it with Sheets I see it empty. 

I'm not doing anything fancy, just a table with string values (no formatting or formulas).
Thanks!

PS.: Great work with this library!!

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by justkawal** [comment]
Yes, it is.

This library picks out the selected and optimised excel structuring from microsoft-excel and google-sheets and combines to use the best from the two.

Latest version: `excel: 2.0.1`
If there is something else for which we can help with, please feel free to re-open the issue again or open a new issue.
