### ISSUE TITLE
Change after rename sheet will lost

### ISSUE THREAD

**Issue by ZhuangXiongfei** [justkawal/excel#104]
Excel excel = Excel.createExcel();
Sheet sheet = newExcel.sheets.values.first;
excel.rename(sheet.sheetName, "newSheetName");
sheet.insertRowIterables([1, 2, 3], 0);  // This will lost
sheet.appendRow(["x", "y", "z"]);  // This will lost, too
List<int>? bytes = await excel.encode();
if(bytes != null) {
    File("pathToFile\\test.xlsx")
      ..createSync(recursive: true)
      ..writeAsBytesSync(bytes);
}

========================
Rename sheet after change is OK.

**Comment by justkawal** [comment]
````dart
Excel excel = Excel.createExcel();

Sheet sheet = newExcel.sheets.values.first;

/// renaming here
excel.rename(sheet.sheetName, "newSheetName");

/// again taking the new object ref
sheet = excel['newSheetName'];

sheet.insertRowIterables([1, 2, 3], 0); // This will lost

sheet.appendRow(["x", "y", "z"]); // This will lost, too

List? bytes = await excel.encode();

if(bytes != null) {
    File("pathToFile\test.xlsx")
        ..createSync(recursive: true)
        ..writeAsBytesSync(bytes);
}
````

**Comment by ZhuangXiongfei** [comment]
Thanks for response. I think it will more convenience to the new readers if add those lines to the example (https://pub.dev/packages/excel#rename-sheet) 

```
/// renaming here
excel.rename(sheet.sheetName, "newSheetName");
/// again taking the new object ref
sheet = excel['newSheetName'];
```
