### ISSUE TITLE
Parsing yields incorrect results for Excel files with duplicate shared string entries

### ISSUE THREAD

**Issue by nextdracool** [justkawal/excel#105]
**What happened?**
I've come across an Excel file which contains duplicate entries in the sharedStrings.xml. It was created entirely in Excel, I suspect some kind of copy-paste caused the duplicate entry. This library does not handle that case correctly.

**Expected result**
The library should correctly handle duplicate shared string entries.

**Actual result**
The  library returns incorrect values for all cells whose shared string entry is after the duplicate entry.

**Tested Versions**
Originally found in `2.0.0-null-safety-3`, also reproduced on `master`.

**Minimal reproducible sample**
Sample File: [DuplicateSharedString.xlsx](https://github.com/justkawal/excel/files/6853779/DuplicateSharedString.xlsx)
````dart
import 'dart:io';
import 'package:excel/excel.dart';

void main(List<String> args) {
  var file = "./DuplicateSharedString.xlsx";
  var bytes = File(file).readAsBytesSync();

  var excel = Excel.decodeBytes(bytes);
  var sheet = excel.sheets[excel.getDefaultSheet()]!;
  // looking in the debugger you can see, that sheet.rows[0] contains [DEF, Test, ABC, null] while Excel displays [ABC, Test, Test, DEF]
}
````

**Potential Solution**
A simple fix is adding the shared string entry regardless of duplication during parsing only.

**Comment by Senecca74** [comment]
this seems to have been fixed with https://github.com/justkawal/excel/commit/486b057135c0ca2ec34407c42463853472653b4b

**Comment by AlexanderJohr** [comment]
I created a new issue explaining the problem in detail and I created a pull request for it: https://github.com/justkawal/excel/issues/182
