### ISSUE TITLE
every version of some_other_library depends on version....

### ISSUE THREAD

**Issue by devsef** [justkawal/excel#112]
Hi.
I tried to solve the issues by following the articles 
https://github.com/justkawal/excel/issues/26
https://github.com/justkawal/excel/issues/25
https://github.com/justkawal/excel/issues/11
but it did not solve the problem

First I get following error at pub get:
`Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and flutter_svg 0.22.0 depends on xml ^5.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with flutter_svg 0.22.0.
And because no versions of flutter_svg match >0.22.0 <0.23.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with flutter_svg ^0.22.0.
So, because wine_region depends on both flutter_svg ^0.22.0 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because wine_region depends on both flutter_svg ^0.22.0 and excel ^1.1.5, version solving failed.)`

After following the mentoined solutons I get following errors:
`Because excel <2.0.0-null-safety depends on archive ^2.0.0 which depends on crypto ^2.0.0, excel <2.0.0-null-safety requires crypto ^2.0.0.
And because google_fonts 2.1.0 depends on crypto ^3.0.0 and no versions of google_fonts match >2.1.0 <3.0.0, excel <2.0.0-null-safety is incompatible with google_fonts ^2.1.0.
So, because wine_region depends on both google_fonts ^2.1.0 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because wine_region depends on both google_fonts ^2.1.0 and excel ^1.1.5, version solving failed.)`

So I can't find any combination of libraries that works. Is there any solution available?

**Comment by neiljaywarner** [comment]
anyupdate on this?

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released fixed many package conflicts.
