### ISSUE TITLE
Can it depend on xml ^5.0.0 ?

### ISSUE THREAD

**Issue by mauritoo** [justkawal/excel#118]
Hi! I'm currently trying to use the package but I'm having problems on solving dependencies. Seems like flutter_svg package uses a newer version of xml package and that generates an inconsistence. See my output below:

`[pvsadmin] flutter pub get
Running "flutter pub get" in pvsadmin...                        
Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and flutter_svg 0.22.0 depends on xml ^5.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with flutter_svg 0.22.0.
And because no versions of flutter_svg match >0.22.0 <0.23.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with flutter_svg ^0.22.0.
So, because pvscontrol depends on both flutter_svg ^0.22.0 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because pvscontrol depends on both flutter_svg ^0.22.0 and excel ^1.1.5, version solving failed.)
exit code 1`

So currently I cant use both packages at the same time. But I would love to try yours!

**Comment by NghiNguyen0604** [comment]
You can ref to version 2.0.0 -null-safety-3. It works for me.

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released fixed many package conflicts.
