### ISSUE TITLE
[FEATURE REQUEST ] Auto Column width/Fit

### ISSUE THREAD

**Issue by elvindesigns** [justkawal/excel#127]
Hi :)

thank you so much for this awesome package

Is it possible to have the auto column width feature or a width adjust feature for a cell.

**Comment by justkawal** [comment]
@elvindesigns Auto-fit is not possible at the moment: #41 

But surely I can give feature to change column with and height manually by code.

and will be actively working on this package from coming week.

**Comment by elvindesigns** [comment]
That will be great. Thanks for the reply. Awesome package👍🏽

**Comment by bertbeck** [comment]
Any progress on the ability to set a column (or cell) width manually? This will be very helpful

**Comment by justkawal** [comment]
@bertbeck 
I think its already implemented and available in newest version: `excel: 2.0.1`.
Can you please check and confirm on the same ?

If you are unable to achieve the desired functionality from excel then feel free to re-open the issue again.
