### ISSUE TITLE
Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and image 3.1.0 depends on xml ^5.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with image 3.1.0.

### ISSUE THREAD

**Issue by Patrick386** [justkawal/excel#128]
Pub get:  excel: ^1.1.5
Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and image 3.1.0 depends on xml ^5.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with image 3.1.0.
And because no versions of image match >3.1.0 <4.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with image ^3.1.0.
So, because pronto depends on both image ^3.1.0 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because pronto depends on both image ^3.1.0 and excel ^1.1.5, version solving failed.)

**Comment by NghiNguyen0604** [comment]
You can ref to version 2.0.0 -null-safety-3. It works for me.

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released fixed many package conflicts.
