### ISSUE TITLE
xml package version error

### ISSUE THREAD

**Issue by Mehrankhan-METRA-RGB** [justkawal/excel#134]
Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 and pdf 3.7.1 depends on xml ^5.1.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with pdf 3.7.1.
And because no versions of pdf match >3.7.1 <4.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with pdf ^3.7.1.
So, because oms depend on both pdf ^3.7.1 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because oms depend on both pdf ^3.7.1 and excel ^1.1.5, version solving failed.)

Kindly upgrade the XML version in a package so that people can use the latest one thank you.

**Comment by NghiNguyen0604** [comment]
You can ref to version 2.0.0 -null-safety-3. It works for me.

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released fixed many package conflicts.
