### ISSUE TITLE
download and open the excel file

### ISSUE THREAD

**Issue by anmolgupta-aeologic** [justkawal/excel#139]
I am generating the excel file and storing it in the firebase and downloading it from there, but the file is not opening.

    File file;
    excel.encode().then((onValue) async {
      print(path);
      file = await File(join(path))
        ..createSync(recursive: true)
        ..writeAsBytesSync(onValue);
      final ref = FirebaseStorage.instance
          .ref()
          .child('excel_files')
          .child(DateTime.now().toString());

      await ref.putFile(file).whenComplete(
            () => print("complete"),
          );
    });

**Comment by justkawal** [comment]
@anmolgupta-aeologic 
Before uploading to firebase, Can you open the file in your system from the path: `File(join(path))` ?

**Comment by FauconSpartiate** [comment]
I'm gonna go ahead and close this issue, as there hasn't been any activity recently.
Be free to open it again if you want to provide more details.
