### ISSUE TITLE
Plz resolve this depedency conflicts issue

### ISSUE THREAD

**Issue by fahadmustafa650** [justkawal/excel#146]
Because excel >=1.0.4 <2.0.0-null-safety depends on xml ^4.1.0 which depends on convert ^2.1.0, excel >=1.0.4 <2.0.0-null-safety requires convert ^2.1.0.
And because json_serializable >=4.0.3 depends on build ^2.0.0 which depends on convert ^3.0.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with json_serializable >=4.0.3.
And because invoiceninja 0.0.9 depends on json_serializable ^4.1.0 and no versions of invoiceninja match >0.0.9 <0.1.0, excel >=1.0.4 <2.0.0-null-safety is incompatible with invoiceninja ^0.0.9.
So, because etf depends on both invoiceninja ^0.0.9 and excel ^1.1.5, version solving failed.
pub get failed (1; So, because etf depends on both invoiceninja ^0.0.9 and excel ^1.1.5, version solving failed.)
exit code 1

**Comment by justkawal** [comment]
@fahadmustafa650 
This issue is not from excel package.
Please refer to Stack-Overflow for further help.

Thanks.
