### ISSUE TITLE
new release with null safety

### ISSUE THREAD

**Issue by felix-ht** [justkawal/excel#147]
Please create a new release with null safety and recent bug fixes! 

Also for some reason the null-safety branch was deleted and not merged?

**Comment by justkawal** [comment]
@felix-ht 
Branch null-safety is now available.

**Comment by felix-ht** [comment]
thanks - any plans on releasing it as a proper - non preview - release? Might also be good to merge it and get rid of the non nullsafe code on master

**Comment by justkawal** [comment]
@felix-ht 
Will surely do that in the coming weekend.

After some more fixes on improper data catching (or copied object referencing) as reported by the users, will then release it on pub.dev

**Comment by blueeyestw** [comment]
@justkawal 
Any updates on stable nullsafety release?

**Comment by selvam920** [comment]
Hi any update?

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released finally added null safety to the stable track.
