### ISSUE TITLE
problem in sheetObject.spannedItems

### ISSUE THREAD

**Issue by Anirban-Plabon** [justkawal/excel#151]
according to documentation sheetObject.spandedItems return a List. My .xlsx file has several merged cells but sheetObject.spannedItems list show empty.
Code:
Sheet sheetObject = excel[table];
          var span=sheetObject.spannedItems;
          print('Spanded Items :');
          print(span);
          print("length of spandedItems:"+sheetObject.spannedItems.length.toString());

output:

I/flutter (11653): Spanded Items :
I/flutter (11653): []
I/flutter (11653): length of spandedItems:0

**Comment by justkawal** [comment]
Sorry for the trouble.
Can you please confirm that are you having this trouble in latest version: `excel: 2.0.1`
If not, please feel free to re-open the issue again.

**Comment by Bes79** [comment]
Same issue. Version 2.1.0

**Comment by hortegag91** [comment]
Any solution?
