### ISSUE TITLE
How i can get count of pages in document ?

### ISSUE THREAD

**Issue by hopheylalaley84** [justkawal/excel#156]
How i can get count of pages in document ?

**Comment by FauconSpartiate** [comment]
You can simply access the `.tables.length` property of your decoded Excel document.

      ByteData data = await rootBundle.load("assets/existing_excel_file.xlsx");
      var bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
      var excel = Excel.decodeBytes(bytes);

      print(excel.tables.length);
