### ISSUE TITLE
Can you support .xls file format?

### ISSUE THREAD

**Issue by tuyennvt** [justkawal/excel#157]
I am working with Excel file format (.xls). Can you help me. Thanks

**Comment by ngdinhkhoa120691** [comment]
I'm developing mac/win app, so I need to support file format (**.xls**).

**Comment by elvindesigns** [comment]
Same here. working with (.xls) file formats at the moment.

**Comment by igdmitrov** [comment]
Hi! I think it can't be solved, because it's absolutely different structure and format.

**Comment by justkawal** [comment]
Sorry not at the moment.
