### ISSUE TITLE
error when reading worksheets, the indexes of the columns read in dart do not match excel, it is as if the columns change order randomly

### ISSUE THREAD

**Issue by insinfo** [justkawal/excel#159]
error when reading spreadsheets, the indexes of the columns read in dart do not match excel, which makes it impossible to import to the database because there is inconsistency, it is as if the columns change order randomly.

### given this worksheet.
![image](https://user-images.githubusercontent.com/12227024/171255279-a8b63e39-b8ff-409c-8f3f-3770582f3dfa.png)

[AUTO DE INFRACAO e AUTO DE CONSTATACAO.xlsx](https://github.com/justkawal/excel/files/8808016/AUTO.DE.INFRACAO.e.AUTO.DE.CONSTATACAO.xlsx)

### the reading result is this: see that the columns do not match
![image](https://user-images.githubusercontent.com/12227024/171255418-027a57a5-1b3b-4c85-82c3-4b1433117392.png)

```dart
void main(List<String> args) async {

  var spreadsheetFilePath =
      'C:/MyDartProjects/notifis/notifis_backend/db/planilhas/AUTO DE INFRACAO e AUTO DE CONSTATACAO.xlsx';
  var bytes = File(spreadsheetFilePath).readAsBytesSync();
  var excel = Excel.decodeBytes(bytes);
  var worksheetsNames = excel.tables.keys;
  for (var sheetName in worksheetsNames) {
    
    if (sheetName == 'AUTO DE INFRACAO') {
      var sheet = excel.tables[sheetName];
      var sheetRows = sheet.rows;
      var rowsLength = sheetRows.length;

      for (var idx = 0; idx < rowsLength; idx++) {
        var row = sheetRows[idx];
        // print(" ${row.map((e) => '${e?.value}').join(' | ')}");
        print(
            "${row[0]?.value} | ${row[1]?.value} | ${row[2]?.value} | ${row[3]?.value} | ${row[4]?.value} | ${row[5]?.value} | ${row[6]?.value} | ${row[7]?.value} | ${row[8]?.value}");
      
      }
      break;
    }    
  }
  exit(0);
}
```

the column with the value "ENEL" was supposed to be in index 2 but to be in index 4, there is also a confusion regarding row data appearing in the wrong row and wrong column.

**Comment by alexandremcp** [comment]
The Lib is experiencing errors when importing the data, shuffling the information displaying in incorrect order.

**Comment by d3ndesign** [comment]
Hi.  Will need to look out for this issue, as am hoping to be able to use this library -- so thanks for the heads-up. 
I think the issue may be related to async/futures, in that some column/row(s) are processed quicker and return faster than previous calls.  There may be ways around this? no async expert, but maybe an id could be passed as part of the request, then re-ordered after all columns/rows are returned. More familiar with networking where bytes can be received out of order across the network and then the need to reorder these before presentation levels.

**Comment by justkawal** [comment]
Sorry for the trouble.
Can you please confirm that are you having this trouble in latest version: `excel: 2.0.1`

**Comment by YancyHsu** [comment]
> Sorry for the trouble. Can you please confirm that are you having this trouble in latest version: `excel: 2.0.1`

version 2.0.1 has the problem

**Comment by DaKar00** [comment]
i am working on a project to extract some data from an excel file, when the project was almost done i noticed that some rows had "shifted" the array one step and was giving me the data from the wrong cell. I have tried changeing the data in the excel file, changed the order of the rows but it just wont give me the correct data, at this point i dont know how to proceed. Is there a another package i can try?

**Comment by navyzhou926** [comment]
I have the same problem. Could not find any solutions

**Comment by marcoredz** [comment]
same issue

**Comment by youssefhegab14** [comment]
Same issue

**Comment by danielR2001** [comment]
same issue, any updates?

**Comment by insinfo** [comment]
@FauconSpartiate any updates?

**Comment by FauconSpartiate** [comment]
Nope, but any help from anyone that is motivated is welcome 👍

**Comment by FauconSpartiate** [comment]
Closing, as this has been fixed.

**Comment by insinfo** [comment]
I just did a test with version 3.0.0 and it seems to be working correctly now

![image](https://github.com/dart-windows/win32/assets/12227024/7c87c1ea-c1e5-4a40-b7d7-2094f192a240)



![image](https://github.com/dart-windows/win32/assets/12227024/6b9bdd40-d63e-4ec4-9165-914f7de85099)


```dart
import 'dart:io';
import 'package:excel/excel.dart';
import 'package:http/http.dart' as http;

void main(List<String> args) async {
  final url =
      'https://github.com/justkawal/excel/files/8808016/AUTO.DE.INFRACAO.e.AUTO.DE.CONSTATACAO.xlsx';
  final resp = await http.get(Uri.parse(url));

  final bytes = resp.bodyBytes;
  final excel = Excel.decodeBytes(bytes);
  final worksheetsNames = excel.tables.keys;
  for (var sheetName in worksheetsNames) {
    if (sheetName == 'AUTO DE INFRACAO') {
      final sheet = excel.tables[sheetName]!;
      final sheetRows = sheet.rows;
      final rowsLength = sheetRows.length;

      for (var idx = 0; idx < rowsLength; idx++) {
        final row = sheetRows[idx];
        // print(" ${row.map((e) => '${e?.value}').join(' | ')}");
        print(
            '${row[0]?.value} | ${row[1]?.value} | ${row[2]?.value} | ${row[3]?.value} | ${row[4]?.value} | ${row[5]?.value} | ${row[6]?.value} | ${row[7]?.value} | ${row[8]?.value}');
      }
      break;
    }
  }
  exit(0);
}

```
