### ISSUE TITLE
Having so many issues with flutter 3.0.2 please could you fix that I cant find nay solution

### ISSUE THREAD

**Issue by fisforfaheem** [justkawal/excel#162]
![image](https://user-images.githubusercontent.com/35878088/174599001-ebf7cc7a-fdbb-47d1-94cb-0b6cd0cc235d.png)

**Comment by igdmitrov** [comment]
Hi! I prepared the pull-request #170 
Hope it works and it will merge in the branch.

**Comment by justkawal** [comment]
If you still face this issue, Please feel free to re-open this issue again.

**Comment by fisforfaheem** [comment]
Please update on pub.dev
