### ISSUE TITLE
Upgrade xml version to 6.1.0 and create new release

### ISSUE THREAD

**Issue by lukaskurz** [justkawal/excel#163]
Hello @justkawal,

I was hoping you could upgrade the current xml version that this package is using to the latest version.
There are a lot of issues (#134, #162 and some more) with a similar request/issue. Through a cascade of transitive dependencies this library is preventing me from using the latest `flutter_svg` version, since it depends on `xml: 6.1.0`, but my translation library `flappy_translator` depends on this package, resulting in a version conflict.

Thanks and keep up the good work :+1:

**Comment by qwertyway** [comment]
I'm having the same issue after upgrading libraries to the latest versions. Upgrade of the dependencies it needed

**Comment by bichoalexis** [comment]
is this project abandoned?

**Comment by igdmitrov** [comment]
Hi! I prepared pull request.
#170 Update version packages.

**Comment by igdmitrov** [comment]
Hi! I prepared the pull-request #170 
Hope it works and it will merge in the branch.

**Comment by blueeyestw** [comment]
> is this project abandoned?

Pub package hasn't been updated in a while but this repo has been making progress

I've been using this in my Pubspec.yaml

```
  excel:
    git: https://github.com/justkawal/excel
```

**Comment by SteveCruise** [comment]
please update

**Comment by justkawal** [comment]
If you still face this issue, Please feel free to re-open this issue again.

**Comment by therealjohnsummer** [comment]
Great library but still getting the same issue : 

`Because flutter_native_splash >=2.2.3 depends on xml ^6.1.0 and excel 2.0.0-null-safety-3 depends on xml ^5.0.2, flutter_native_splash >=2.2.3 is incompatible with excel 2.0.0-null-safety-3.
`

Can we bump up the xml dependency to the latest @justkawal

**Comment by therealjohnsummer** [comment]
@justkawal Note , referencing directly to your git works ... The issue is with not having the published version synced in pub.dev ...
