### ISSUE TITLE
How can I skip the first row in the excel file and read the others ? 

### ISSUE THREAD

**Issue by ET-TOUNANI** [justkawal/excel#165]

**Comment by ET-TOUNANI** [comment]
solved

**Comment by yinkyAde** [comment]
How can I skip the first row in the excel file, i keep encountering a format exception

S/No. | RADET Period (yyyy-mm-dd) | State | LGA | Facility Name | LAMIS UIDPatient Id | Hospital Num | Household Id | Unique Number | Sex | Marital Status | Weight (Kg) | Date of Birth (yyyy-mm-dd)  - this is the header i.e first row

Error: FormatException: Date of Birth (yyyy
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 229:5             parse
packages/radet_calculator/screens/web/dashboad_radet_screen.dart 230:44       <fn>
packages/flutter/src/widgets/framework.dart 1114:30                           setState
packages/radet_calculator/screens/web/dashboad_radet_screen.dart 131:11       pickFile
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
dart-sdk/lib/async/zone.dart 1653:54                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 430:9                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
