### ISSUE TITLE
Question : How to make cell value on several cells ?

### ISSUE THREAD

**Issue by Tom3652** [justkawal/excel#171]
Hello @justkawal thanks for the package ! 

How can i make this using your plugin please ? The equivalent in excel is : `B2:M2`

![Capture d’écran 2022-08-12 à 15 17 01](https://user-images.githubusercontent.com/32631467/184361631-289a57c3-0e7e-4129-923c-f95c1e05a273.png)

**Comment by justkawal** [comment]
This is called spanning of rows and columns.
You can easily do this from this package.

Questions like these will be answered on stack-overflow easily.
