### ISSUE TITLE
add an option to set the column width to a fixed value or an option to adjust the column width according to the content.

### ISSUE THREAD

**Issue by insinfo** [justkawal/excel#174]
add an option to set the column width to a fixed value or an option to adjust the column width according to the content.

**Comment by igdmitrov** [comment]
Hi! It's possible right now, you can check my video on Youtube about it:
https://www.youtube.com/watch?v=S_Ggw5uNWUI

**Comment by justkawal** [comment]
@insinfo 
I think it's already implemented.
Can you please confirm that are you able to achieve this with latest version: `excel: 2.0.1`
