### ISSUE TITLE
Stil not updated on pub.dev, Please update on pub.dev to really use it easily and please use flutter 3.0.5

### ISSUE THREAD

**Issue by fisforfaheem** [justkawal/excel#176]
![image](https://user-images.githubusercontent.com/35878088/186659801-0251ad20-d00a-4922-a15f-99417b703889.png)

**Comment by Ronjack** [comment]
searched here for the latest fork 

https://techgaun.github.io/active-forks/index.html#justkawal/excel 

this looks good 

https://github.com/justkawal/excel/compare/null-safety...dukefirehawk:excel:master

> ![image](https://user-images.githubusercontent.com/35878088/186659801-0251ad20-d00a-4922-a15f-99417b703889.png)

**Comment by fisforfaheem** [comment]
please tell how to use this?? extension/fork in my current project

**Comment by fisforfaheem** [comment]
any updateS???

**Comment by fisforfaheem** [comment]
on pub.dev

**Comment by fisforfaheem** [comment]
???

**Comment by fisforfaheem** [comment]
Can anyone reply

**Comment by FauconSpartiate** [comment]
You can specify to use the prerelease version of the package by changing the entry to `excel: ^2.0.0-null-safety-3` instead of `excel: ^1.1.5` in your `pubspec.yaml`.
A new version should be released today by @justkawal, fixing a lot of conflict issues related to the SDK and the XML package.

**Comment by justkawal** [comment]
Released

**Comment by fisforfaheem** [comment]
Omg thanks would help us a lot

**Comment by fisforfaheem** [comment]
still not showing on pub.dev though

**Comment by fisforfaheem** [comment]
??

**Comment by FauconSpartiate** [comment]
The latest release on pub.dev is `2.0.1` (https://pub.dev/packages/excel) and implements the features you wanted.
What version are you seeing?
