### ISSUE TITLE
[Feature] Set Row Height

### ISSUE THREAD

**Issue by RogerBrusamarello** [justkawal/excel#178]
There's a way to set to height of the row?
I need put some images in table's header, but when I save the file, the first row just return to original size.

Original Header
<img width="1014" alt="Captura de Tela 2022-09-20 às 10 46 37" src="https://user-images.githubusercontent.com/34141109/191274735-4e4a4ab4-cd56-4b3b-87f1-bf5c5bcb0fc4.png">

After saving using package
<img width="1329" alt="Captura de Tela 2022-09-20 às 10 49 35" src="https://user-images.githubusercontent.com/34141109/191275506-6c5014c1-61a9-4f9e-be20-866a1d9c16b5.png">

How can I fix it?

**Comment by loic-hamdi** [comment]
@justkawal  any news on this feature implementation?  [https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L931](https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L931)

**Comment by FauconSpartiate** [comment]
Fixed in #245 and released in `3.0.0`
