### ISSUE TITLE
xml version mismatch with auto_route_generator

### ISSUE THREAD

**Issue by thamarakshan-pilla** [justkawal/excel#179]
Please update the xml version as the auto_route_generator also has a dependency on the xml package.

![Capture](https://user-images.githubusercontent.com/69303422/193434232-47b1de7f-4586-4b70-afa2-0c067f3cc8c2.PNG)

**Comment by dna-f** [comment]
Hi guys, 
thanks for your great work!
I'm using excel 2.0.0-null-safety-3 but some other libs require xml ^6.0.0, so i override dependencies to that version
Are you going to update dependencies soon?

**Comment by FauconSpartiate** [comment]
This issue has now been fixed, version 2.0.1 that just released fixed many package conflicts.
