### ISSUE TITLE
Different color on different lines in a cell

### ISSUE THREAD

**Issue by majdi21** [justkawal/excel#180]
Hello,

   I'm trying to create an excel where in a cell I would have multiple lines, each line has some colored text. The text color can vary based on some rules (details of the rules are irrelevant to this question).

   I can create the excel and have multiple lines in my cells, but I'm unable to set different colors to different lines in the same cell. I tried to open an excel in vi and I saw that it is using xml and adding tags like <color rgb="FF00B0F0"/> for blue. I tried to add that but the value just ends up displaying that as a string. How can I accomplish this?

Thank you,

**Comment by justkawal** [comment]
@majdi21 
Sorry for the delayed response.
Can you please confirm if you're having the trouble with version: `excel: 2.0.1`

**Comment by justkawal** [comment]
As its been a while since there was any response so, I'm closing this issue considering it as resolved.

Please feel free to re-open the issue if you find any difficulty !!
