### ISSUE TITLE
Shared Strings are treated as plain text which corrupts the shared strings registry when the texts contain styling

### ISSUE THREAD

**Issue by AlexanderJohr** [justkawal/excel#182]
Shared Strings are treated as plain text. This causes the shared strings registry to be corrupt, when the texts contain styling.

Take this excel file for example. 

![image](https://user-images.githubusercontent.com/7449711/198567859-19341751-2675-43e9-8241-d3344d57a48c.png)
[superscriptExample.xlsx](https://github.com/justkawal/excel/files/9889250/superscriptExample.xlsx)

After this file is parsed with the `excel` package and then saved again, the output file is this:

![image](https://user-images.githubusercontent.com/7449711/198569162-2d3e6a32-d3c6-4fe0-9f40-12312b298986.png)
[superscriptExampleOut.xlsx](https://github.com/justkawal/excel/files/9889255/superscriptExampleOut.xlsx)
This file is generated by [this test](https://github.com/justkawal/excel/blob/1b4ed0739ae72c970a30e50964c046f91269f7c3/test/excel_test.dart#L97-L121): 

This inner cell styles are missing which could be treated as a known limitation. But much more dangerous is, is that the cell positions are incorrect.

Here is why:

Both A1 and A2 contain the same text, but A2 is bold. This style is normally stored in `styles.xml` and a reference to this style is stored on the cell in `sheet1.xml`. But this time it is different. Because the cell also contains an inner style, the style indicating that the whole cell is bold is now not stored in `styles.xml` anymore, but now it is stored in `sharedStrings.xml`.

This is the shared string for A1:

```xml
    <si>
        <r>
            <t xml:space="preserve">Text </t>
        </r>
        <r>
            <rPr>
                <vertAlign val="superscript"/>
                <sz val="11"/>
                <color theme="1"/>
                <rFont val="Calibri"/>
                <family val="2"/>
                <scheme val="minor"/>
            </rPr>
            <t>and superscript text</t>
        </r>
    </si>
```

This is the shared string for A2. Notice the `<b/>` below the `<rPr>` which is missing in A1.

```xml
    <si>
        <r>
            <t xml:space="preserve">Text </t>
        </r>
        <r>
            <rPr>
                <b/>
                <vertAlign val="superscript"/>
                <sz val="11"/>
                <color theme="1"/>
                <rFont val="Calibri"/>
                <family val="2"/>
                <scheme val="minor"/>
            </rPr>
            <t>and superscript text</t>
        </r>
    </si>
```

Because of this, such styles must be parsed as well. But the `excel` package does not parse all the nodes. It only parses the content of the `<t>` nodes and concatenates them. This causes the style to be missing. But it also causes the registry to treat the values of A1 and A2 to be the same. This is because the key in the `_SharedStringsMaintainer` is generated from the concatenated plain text from all `<t>` nodes as seen [here](https://github.com/justkawal/excel/blob/eb091ba91963773741b7f0f8a3378269300a8ed2/lib/src/parser/parse.dart#L144-L150). This is why a mismatch happens, when there are two different texts with different styling but same plain text. That is why the the two texts get the same index and also why all following shared strings get a wrong index which is decreased by one. That explains the incorrect cell positions, because the index of the shared string, the cell is referencing to, is not changing.

The error was tried to fix in https://github.com/justkawal/excel/commit/486b057135c0ca2ec34407c42463853472653b4b by just counting the index up every time, even when is the newly parsed string is already present, but this introduces new bugs and also causes saved excel files to be corrupt.
That change was removed again by https://github.com/justkawal/excel/commit/e8adeaf8e6c2f87dd4eb9f3c6da8d6140b9fb304.

This problem is also party discussed in issue https://github.com/justkawal/excel/issues/105.

I created a fork where I resolve this issue with this pull request: https://github.com/justkawal/excel/pull/183

**Comment by justkawal** [comment]
Thanks for the in-depth explanation and for the PR that you made.
It's so great to have people like you on open-source. Thanks Again brother....

**Comment by AlexanderJohr** [comment]
I'm glad you appreciated it 😊
