### ISSUE TITLE
Skip the first row in the excel file

### ISSUE THREAD

**Issue by yinkyAde** [justkawal/excel#188]
How to skip first row 
 
S/No. | RADET Period (yyyy-mm-dd) | State | LGA | Facility Name | LAMIS UIDPatient Id | Hospital Num | Household Id | Unique Number | Sex | Marital Status | Weight (Kg) | Date of Birth (yyyy-mm-dd) - this is the header i.e first row

Error: FormatException: Date of Birth (yyyy
dart-sdk/lib/internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49 throw
dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 229:5 parse
packages/radet_calculator/screens/web/dashboad_radet_screen.dart 230:44
packages/flutter/src/widgets/framework.dart 1114:30 setState
packages/radet_calculator/screens/web/dashboad_radet_screen.dart 131:11 pickFile
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50
dart-sdk/lib/async/zone.dart 1653:54 runUnary
dart-sdk/lib/async/future_impl.dart 147:18 handleValue
dart-sdk/lib/async/future_impl.dart 766:44 handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13 _propagateToListeners
dart-sdk/lib/async/future_impl.dart 430:9 callback
dart-sdk/lib/async/schedule_microtask.dart 40:11 _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5 _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15

**Comment by yinkyAde** [comment]
@justkawal

**Comment by thegioiso** [comment]
@yinkyAde this will help
```
int i = 0;
for (var row in excel.tables[$yourSheetName]!.rows) {
if (i != 0) {
//do something here
}
}
```
