### ISSUE TITLE
The data read is wrong

### ISSUE THREAD

**Issue by read0nly** [justkawal/excel#193]
![321670990921_ pic_hd](https://user-images.githubusercontent.com/25766500/207503529-98e789d5-7499-4628-a155-60d286e28cd0.jpg)

On the left is the data read by python, and on the right is the data read by excel.
The data in the previous row has gone to the next row, and the data in the next row is missing.
Here is the test file:
[测试导入.xlsx](https://github.com/justkawal/excel/files/10224210/default.xlsx)

**Comment by justkawal** [comment]
Sorry for the trouble.
Can you please confirm that are you having this trouble in latest version: `excel: 2.0.1`

**Comment by justkawal** [comment]
@read0nly
As its long to get any response, I think the error is fixed.

If the issue still persists then please feel free to re-open the issue again.
