### ISSUE TITLE
Outdated release on pub.dev

### ISSUE THREAD

**Issue by FauconSpartiate** [justkawal/excel#194]
The last update of this package on pub.dev is 2 years old, even the prerelease version is 1.5 years old. 
The last revision of the repo should be uploaded to pub.dev to add all the fixes that have been implemented since then.
In a real project, this outdated release generates a ton of package version conflicts, that are not necessary, and already got fixed on this repo. As many other packages depend on this one, everything is just a giant mess of new and old transitive versions.

So please, @justkawal, an updated preview release on pub.dev is urgently needed.

**Comment by justkawal** [comment]
Thanks for the reminder @FauconSpartiate .
I'll do it today 💯.
