### ISSUE TITLE
save file issue

### ISSUE THREAD

**Issue by enghussein13** [justkawal/excel#195]
hi ,
when i run my project and after i save the excel file this error is raised to me:
E/flutter ( 7901): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: Creation failed, path = 'Directory: '' (OS Error: Read-only file system, errno = 30)
E/flutter ( 7901): #0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
E/flutter ( 7901): #1      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter ( 7901): #2      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter ( 7901): #3      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter ( 7901): #4      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter ( 7901): #5      _Directory.createSync (dart:io/directory_impl.dart:128:16)
E/flutter ( 7901): #6      _File.createSync (dart:io/file_impl.dart:270:14)
E/flutter ( 7901): #7      ExcelPage.build.<anonymous closure> (package:readings_app/excel.dart:55:17)
E/flutter ( 7901): <asynchronous suspension>
E/flutter ( 7901):

**Comment by FauconSpartiate** [comment]
Look at the error message, it says ` Read-only file system`. The OS is denying access to the directory you are saving your file to.
Try saving it somewhere else, or getting the OS to give you access to that directory...
