### ISSUE TITLE
Async decoding Excel file

### ISSUE THREAD

**Issue by xzghx** [justkawal/excel#201]
Is it possible to make  `Excel.decodeBytes(fileBytes);` command async?
the app UI freezes for large excel files.

**Comment by FauconSpartiate** [comment]
Making the method asynchronous wouldn't change anything, as the thread isn't waiting for something to happen, it is actively doing heavy calculations and so blocking the main thread.

What you could use is an isolate like described in this comment: https://github.com/justkawal/excel/issues/96#issuecomment-903656480

If you want to learn more about it, you can take a look at this video: https://www.youtube.com/watch?v=5AxWC49ZMzs
