### ISSUE TITLE
Automate pub.dev publishing

### ISSUE THREAD

**Issue by justkawal** [justkawal/excel#215]
- [ ] After 2-3 approvals the feature should be merged to branch `null-safety`.
- [ ] Creating tag will help to publish easily.

**Comment by justkawal** [comment]
@FauconSpartiate What's your thought on this ?

**Comment by FauconSpartiate** [comment]
This is a very good idea, it cuts down on the long update delays of you working.
I'm sure a lot of GitHub actions already exist to do this...

**Comment by justkawal** [comment]
Configuring and testing....

**Comment by FauconSpartiate** [comment]
Don't forget to also automatically bump the version in pubspec.waml, which is already out of date after my PR 😅

**Comment by justkawal** [comment]
Fixed with #216 

- Done, that manually for now.
- Used custom publishing.
- Release `2.0.3` to pub.dev with automatic publishing ✅

**Comment by justkawal** [comment]
Restricted direct pushes to `publish` for @justkawal also.
