### ISSUE TITLE
cannot decode bytes when excel file has filter.

### ISSUE THREAD

**Issue by hanvit4** [justkawal/excel#223]
cannot decode bytes when excel file has filter. (data -> filter in excel ribon menu)

**Comment by FauconSpartiate** [comment]
Could you provide some code that makes this error occur, and also an excel file?
This will help us find the bug easier.

**Comment by FauconSpartiate** [comment]
Not reproducible on `3.0.0`.
Feel free to open a new issue if you find a specific usecase where it doesn't work.
