### ISSUE TITLE
FR: Excel preview & preview thumbnail from url

### ISSUE THREAD

**Issue by sirwes** [justkawal/excel#225]
Hi,

In my flutter web application, users can send other users excel files. I would like a way to 
1. Preview the excel file in a thumbnail (like they do on Slack)
2. Open and view the whole excel file from a URL.

My use case is that the uploaded excel file goes to my company's storage account and can be accessed via URL, but I don't necessarily want to download it to the user's local device.

Is this something within the scope of the package?

**Comment by Taoduhui** [comment]
No, this lib is only provide an easy way to process excel programmatically.
if you want to implement your requirements, you have to do a lot of work in UI dev.

**Comment by sirwes** [comment]
I totally understand not wanting to implement item 1, but I would think that item 2 would be a part of the package - the ability to programmatically import/open an excel file from a URL. Do you still disagree?

**Comment by Taoduhui** [comment]
> I totally understand not wanting to implement item 1, but I would think that item 2 would be a part of the package - the ability to programmatically import/open an excel file from a URL. Do you still disagree?

You still have to find another package instead this ,I think. Both of 1 and 2, you need a user interface for your user, you need a data grid, such as pluto_grid or syncfusion's products. this package just provide you the ability of reading and writing xlsx file. if you need a free plan for your requirements. you can use this package to operate the xlsx, then find other data grid to present the data.

**Comment by Taoduhui** [comment]
if you just want to read from a URL, you can GET the url to memory, than decode it, this package provide the api to do this.
