### ISSUE TITLE
Fail to parse duplicated shared strings

### ISSUE THREAD

**Issue by mingpepe** [justkawal/excel#230]
[duplicated_shared_strings.xlsx](https://github.com/justkawal/excel/files/11339309/duplicated_shared_strings.xlsx)

In #182, @AlexanderJohr explained about shared strings. Then #183, seems assume that no duplicated data in shared string table, I agree with it but found that is wrong.

Here is the data extract from excel

Sheet data
```
<sheetData>
    <row r="1" spans="1:1" x14ac:dyDescent="0.25">
        <c r="A1" s="1" t="s">
            <v>0</v>
        </c>
    </row>
    <row r="2" spans="1:1" x14ac:dyDescent="0.25">
        <c r="A2" s="1" t="s">
            <v>1</v>
        </c>
    </row>
    <row r="3" spans="1:1" x14ac:dyDescent="0.25">
        <c r="A3" s="1" t="s">
            <v>1</v>
        </c>
    </row>
</sheetData
```
SST
```
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="3" uniqueCount="2">
    <si>
        <t>[5]</t>
        <phoneticPr fontId="3" type="noConversion"/>
    </si>
    <si>
        <t>[5]</t>
        <phoneticPr fontId="3" type="noConversion"/>
    </si>
</sst>
```

Hence shared strings will not be parsed correctly. I'm not sure why duplicated shared string exist.

**Comment by justkawal** [comment]
I think this issue is not happening in the latest version.
If you encounter the same issue please feel free to re-open the issue again.

Thanks.

**Comment by tim1mmr** [comment]
This issue is still present in the latest version since the "Optimizations (#290)" change to shared_strings.dart.
The putIfAbsent code only runs for new keys, so duplicates are ignored.
