### ISSUE TITLE
Facing issue on Excel.decodeBytes(bytes) 

### ISSUE THREAD

**Issue by Dharaneshvar** [justkawal/excel#242]
Unhandled Exception: Invalid argument(s): DateTime is outside valid range: 9112646586256480
#0      new DateTime._withValue (dart:core/date_time.dart:413:7)
#1      DateTime.add (dart:core-patch/date_patch.dart:200:16)
#2      Parser._parseCell (package:excel/src/parser/parse.dart:594:20)
#3      Parser._parseRow.<anonymous closure> (package:excel/src/parser/parse.dart:520:7)
#4      Iterable.forEach (dart:core/iterable.dart:346:35)
#5      Parser._parseRow (package:excel/src/parser/parse.dart:519:22)
#6      Parser._parseTable.<anonymous closure> (package:excel/src/parser/parse.dart:500:7)
#7      Iterable.forEach (dart:core/iterable.dart:346:35)
#8      Parser._parseTable (package:excel/src/parser/parse.dart:499:22)
#9      Parser._parseContent.<anonymous closure> (package:excel/src/parser/parse.dart:160:9)
#10     Iterable.forEach (dart:core/iterable.dart:346:35)
#11     Parser._parseContent (package:excel/src/parser/parse.dart:158:39)
#12     Parser._startParsing (package:excel/src/parser/parse.dart:18:5)
#13     new Excel._ (package:excel/src/excel.dart:75:12)
#14     _newExcel (package:excel/src/excel.dart:17:20)
#15     new Excel.decodeBytes (package:excel/src/excel.dart:85:12)

**Comment by FauconSpartiate** [comment]
Could you provide an example file where the error shows up?
This will help us to investigate the issue
