### ISSUE TITLE
Can be used for xls excel files? Facing FormatException: Could not find End of Central Directory Record for xls file.

### ISSUE THREAD

**Issue by xzghx** [justkawal/excel#243]
Hi,
I face this error while trying to read a xls excel file. 

`FormatException: Could not find End of Central Directory Record` 

Is this related to xls format? is there any way to read a xls excel file?

**Comment by FauconSpartiate** [comment]
Could you provide an example file where the error shows up?
This will help us to investigate the issue

**Comment by chipnetics** [comment]
HI, I'm not the OP but have the same issue as them and a couple findings as well.

I got the `FormatException: Could not find End of Central Directory Record` when trying to run the library on a .xls that was extracted directly from a web application, and downloaded to the desktop. 

Unfortunately I can't share the xls as it has proprietary info... so I deleted the stuff in the file, put in some dummy data, and resaved (still) as .xls (97-2003). However then the error changes to `Unsupported operation: Excel format unsupported.`  So whatever modern Excel does with saving, it seems the errors change.  Thus this may be difficult to replicate....

The web application in question that is generating the xls is rather "legacy", so it may be that older "true" ways of saving .xls had a nuance to them.  If someone had a original version of old school Excel and could make a dummy workbook, that would be the best way to test.

**Comment by sanburnn** [comment]
yup i got same error `Unsupported operation: Excel format unsupported.` when import .xls format @FauconSpartiate

**Comment by FauconSpartiate** [comment]
.xls files are indeed not supported, as described in many issues that are already closed.

But @chipnetics idea of throwing the correct error to let the user know it's good, I'll try to do that when I can.

**Comment by FauconSpartiate** [comment]
Here is a file I found that throws the original error (`FormatException: Could not find End of Central Directory Record`): 
[file_example_XLS_10.xls](https://github.com/justkawal/excel/files/12269607/file_example_XLS_10.xls)

**Comment by FauconSpartiate** [comment]
Fixed in #258 

(Actually not fixed, just clarified that it is not supported)

**Comment by sanburnn** [comment]
@FauconSpartiate oke thankyou
