### ISSUE TITLE
Wrong Data. Lost Data, Null Data

### ISSUE THREAD

**Issue by Danilz-2706** [justkawal/excel#244]
I have an excel file. I import to get data from this file. However, to line 1476, I lost data and wrong data.

I downgraded another version but it still doesn't work.

Flutter doctor:
![4](https://github.com/justkawal/excel/assets/79782235/f2c0be3b-a5b9-4f71-b371-388192b21656)

My Project:
![5](https://github.com/justkawal/excel/assets/79782235/87a1e324-e83b-4717-8e38-fb5dc3717eaf)

Excel File:
![2](https://github.com/justkawal/excel/assets/79782235/0b5b00ba-1b7c-453c-b136-063a4b210b53)

Red: Data null.
Yellow: Skip row data between previous row and next row.
Grey: Lost Data.

Error:
![3](https://github.com/justkawal/excel/assets/79782235/bbde322a-8aca-461d-9c4b-d9bec4a27398)

***Please help me!

**Comment by nfrawley93** [comment]
In case you haven't updated. Try using the newest commit in this repo. The PubDev version has not been updated yet.
Pull #240 should address this issue!
