### ISSUE TITLE
default column width

### ISSUE THREAD

**Issue by bobosette** [justkawal/excel#251]
Hi everybody. I want to build an excel file with 10 columns with a default with. How can I do it?

I tried with a for

`sheet.setColWidth(columnIndex, 30.0)`

but it sets the width only for last column.

Thank you

**Comment by FauconSpartiate** [comment]
Fixed and implemented `setDefaultColWidth()` in #245.

Will be published in next release soon™

**Comment by bobosette** [comment]
Ok thank you. And when do you think next release will come?

Il Sab 29 Lug 2023, 18:07 Faucon ***@***.***> ha scritto:

**Comment by FauconSpartiate** [comment]
Currently prepping it, then we'll have to wait for the owner to approve the PR...

Max a week I guess

**Comment by bobosette** [comment]
Ok thank you

Il Sab 29 Lug 2023, 20:47 Faucon ***@***.***> ha scritto:

**Comment by bobosette** [comment]
Hi. Sorry do you have some news about the official update? I need this fix
for a production project

Il giorno sab 29 lug 2023 alle ore 20:48 Roberto Bobo Prandin <
***@***.***> ha scritto:

**Comment by FauconSpartiate** [comment]
Progress tracked in #255, which also depends on #254
