### ISSUE TITLE
Basic parsing example yields bogus results

### ISSUE THREAD

**Issue by chipnetics** [justkawal/excel#259]
**EDIT: The below bug is only on the latest pub.dev release 2.1.0 (which is 4 months old).  It appears to have been fixed at some point since when pulling from git instead of pub.dev.**

Hi,  this is a great library... and it works 99% except a weird example which I've uploaded where there appears to be some sort of stack corruption.  I've attached the sample .xlsx.  If you run the code below against it you will find the wrong results.

[example.xlsx](https://github.com/justkawal/excel/files/12294047/example.xlsx)

The error persists even if you paste-value the data to a new workbook, so it shouldn't be related to any file corruption.

Code to compile and run exe in same directory is below.  Very simple example, read xlsx and output the data in tab-delimited.

```dart
import 'dart:io';
import 'package:excel/excel.dart';

void main() async {
  final files =
      Directory('.').listSync().where((f) => f.path.endsWith('.xlsx')).toList();

  final outFile = File('merged.txt');
  final outStream = outFile.openWrite();

  int fileNum = 1;

  print('Detected ${files.length} Files');

  for (var file in files) {
    print('Processing file [${file.path}] ::: $fileNum of ${files.length}');

    var excel = Excel.decodeBytes(File(file.path).readAsBytesSync());
    var sheet = excel.tables['Report'];

    if (sheet == null) continue;

    var mutRows = sheet.rows.toList();

    for (var row in mutRows) {
      var rowData = row.map((e) => e?.value).toList();
      outStream.writeln(rowData.join('\t'));
    }

    fileNum++;
  }

  print('Done processing ${files.length} files');
  await outStream.flush();
  await outStream.close();
}
```

Here is the resulting errors in the output (circled in red):

![errors](https://github.com/justkawal/excel/assets/48262878/c80c0f9f-7525-497f-bffb-20f774e85d4d)

It *think* it's something related to the way the library indexes values out of sharedStrings.xml but not sure.   A super weird observation is that if I replace a few of the values on the rows below the error disappears.

![changes](https://github.com/justkawal/excel/assets/48262878/3e0c88c2-f9d2-44e3-b119-1c118e2814a2)

**Comment by FauconSpartiate** [comment]
Fixed in `3.0.0` release.
