### ISSUE TITLE
Reading larger xlsx files is too slow

### ISSUE THREAD

**Issue by DeaJason** [justkawal/excel#262]
The plug-in is easy to use, but its performance is poor, and it is not friendly to large files. It takes 4-5 minutes for a 4M file. Do you consider improving the performance of reading large files?

**Comment by paulinofonsecas** [comment]
I entered this repository exactly through this problem. I hope the creator or another maintainer can resolve it as soon as possible.

**Comment by paulinofonsecas** [comment]
Checkout this comment #96

**Comment by FauconSpartiate** [comment]
You can use isolates to run the number crunching on a different thread, while keeping the UI thread smooth.
https://api.flutter.dev/flutter/foundation/compute.html?ref=blog.flutter.wtf

**Comment by FauconSpartiate** [comment]
@DeaJason @paulinofonsecas Fixed in #290
