### ISSUE TITLE
Excel complains when opening workbook created by this plugin

### ISSUE THREAD

**Issue by rlfolden** [justkawal/excel#287]
I create a workbook with multiple tabs using this plugin but when I open the workbook with Excel it says:
Alert: We found a problem with some content in 'RenewalMailing_Final_2023-10  (252).xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

I click Yes and Excel says: Excel was able to open the file by repairing or removing the unreadable content.
When I click View, a log is opened with the following:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>Repair Result to RenewalMailing_Final_2023-10  (252)2.xml</logFileName><summary>Errors were detected in file '/Users/rudyfoldenMBP/Desktop/RenewalMailing_Final_2023-10  (252).xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Worksheet properties from /xl/workbook.xml part (Workbook)</repairedRecord></repairedRecords></recoveryLog>

The workbook seems to be good although then last Tab generated, has the Header put on the bottom instead of the top.

**Comment by KayaYazilim** [comment]
Same issue, is there any update on this?

**Comment by justkawal** [comment]
Can you try the version:
```yaml
excel: ^4.0.0
```
