### ISSUE TITLE
error during save with cell double

### ISSUE THREAD

**Issue by FeliceT57** [justkawal/excel#294]
the following function:

void createExcel() async {
    var excel = Excel.createExcel();
    Sheet sheetObj = excel['Sheet1'];
    var cell = sheetObj.cell(CellIndex.indexByString('A1'));
    cell.value = DoubleCellValue(10.50);
    var fileToBytes = excel.save(fileName: 'Esempio.xlsx');
  }
  
stops on the last instruction with the message:
  
 Error: Exception: null does not work for DoubleCellValue

**Comment by FeliceT57** [comment]
My flutter doctor -v

[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Versione 10.0.19045.3693], locale it-IT)
    • Flutter version 3.13.6 on channel stable at c:\Users\Daniele\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 weeks ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Daniele\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.6.33723.286
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.84.2)
    • VS Code at C:\Users\Daniele\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.78.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Versione 10.0.19045.3693]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 119.0.6045.200
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 119.0.2151.93

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by mellowcello77** [comment]
@FeliceT57 How does "cellstyle" solve the issue? Please can you post some code with your solution. This is still an issue!

**Comment by mellowcello77** [comment]
This is still an issue, please open the ticket.

**Comment by allato** [comment]
this will be fix to this pr https://github.com/justkawal/excel/pull/311

**Comment by FeliceT57** [comment]
CellStyle sn = CellStyle(numberFormat: NumFormat.standard_0);
cell = sheetObj.cell(CellIndex.indexByString('C$j'));
cell.value = DoubleCellValue(element.quantita);
cell.cellStyle = sn;

**Comment by mellowcello77** [comment]
Has this gone to stable release yet? Will it be in 4.0.3?

**Comment by mellowcello77** [comment]
Please help me understand when this PR is pushed out and in which version this fix will be?
