### ISSUE TITLE
Formula value is not recalculated

### ISSUE THREAD

**Issue by zaytri** [justkawal/excel#30]
**Output:**
```
A1: 1
B1: 3
C1: A1 + B1 = 4
A1: 1
B1: 5
C1: A1 + B1 = 4
```

**Code:**
```dart
import 'dart:io';
import 'package:path/path.dart';
import 'package:excel/excel.dart';

final String FILE_NAME = 'Book2.xlsx';
final String SHEET_NAME = 'Sheet1';
final File file = File(join(FILE_NAME));
final Excel excel = Excel.decodeBytes(file.readAsBytesSync());

void main(List<String> args) async {
  var cell = getData(0, 0);
  var cell2 = getData(1, 0);
  var formulaCell = getData(2, 0);
  print('${cell.cellId}: ${cell.value}');
  print('${cell2.cellId}: ${cell2.value}');
  print('${formulaCell.cellId}: ${formulaCell.value.formula} = ${formulaCell.value.value}');
  setValue(1, 0, 5);
  
  cell = getData(0, 0);
  cell2 = getData(1, 0);
  formulaCell = getData(2, 0);
  print('${cell.cellId}: ${cell.value}');
  print('${cell2.cellId}: ${cell2.value}');
  print('${formulaCell.cellId}: ${formulaCell.value.formula} = ${formulaCell.value.value}');
}

dynamic getData(int col, int row) {
  return excel[SHEET_NAME].row(row)[col];
}

void setValue(int col, int row, dynamic value) {
  excel.updateCell(SHEET_NAME, CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row), value);
}
```

**Attachments:**
[Book2.xlsx](https://github.com/kawal7415/excel/files/4783089/Book2.xlsx)

**Environment:**
Dart VM version: 2.8.1 (stable) (Thu Apr 30 09:25:21 2020 +0200) on "macos_x64"
Excel package version: 1.0.9
MacOS version: 10.15.5

**Comment by ialameh** [comment]
Hi,
I think the formula function is not yet available, it is in the works

**Comment by Dararii** [comment]
Is there any workaround for this?

**Comment by justkawal** [comment]
@Dararii For now there is no workaround for this as I am thinking a way to implement the already created context free grammer for formula calculation. 

I am not thinking for going on the approach of RegExp approach as this will be overhead and might result in slow response also understanding the CFG and then implementing it in dart might take a while.

**Comment by MalikSamiAwan** [comment]
@justkawal @masteradit same problem any suggestions
