### ISSUE TITLE
Exception: null does not work for DateTimeCellValue

### ISSUE THREAD

**Issue by Epiwish** [justkawal/excel#300]
Hey 👋

I'm using excel package in one of my Flutter Web projects. Somehow, DateTimeCellValue always throw this exception:

```
Exception: null does not work for DateTimeCellValue
```

I'm using it like this:

```dart
// log.startTime is a iso8601String
final startTime = DateTime.parse(log.startTime);

final myCell = DateTimeCellValue(
   year: startTime.year,
   month: startTime.month,
   day: startTime.day,
   hour: startTime.hour,
   minute: startTime.minute,
   second: startTime.second,
),
```

I thought something wrong with my startTime value first, but it still throws same error with this code:

```dart
final myCell = DateTimeCellValue(
   year: 1,
   month: 1,
   day: 1,
   hour: 1,
   minute: 1,
   second: 1,
),
```

Even with the hardcoded version. throws same error.
Any help would be great. Thank you

**Comment by AbhiralJain** [comment]
@Epiwish Hi, If you want to update cell using DateTimeCell value, you need to provide the format using numberFormat parameter in cellStyle.

Here is an example:
sheetObject.updateCell(
   CellIndex.indexByString('C$i'),
   DateTimeCellValue(
      year: 1,
      month: 1,
      day: 1,
      hour: 1,
      minute: 1,
      second: 1,
   ),
   cellStyle: CellStyle(
      numberFormat: NumFormat.defaultDate,
   ),
);

**Comment by zxkfall** [comment]
I met the same question when using save method to save excel, This is my code:
```
var excel = Excel.createExcel();
    Sheet sheetObject = excel['Sheet1'];

    sheetObject.appendRow([
      const TextCellValue('Date'),
      const TextCellValue('Amount'),
      const TextCellValue('Type'),
      const TextCellValue('Kind'),
      const TextCellValue('Description')
    ]);
    var billings = await GetIt.I<BillingRepository>().billings();
    for (var billing in billings) {
      developer.log('message, ${DateTimeCellValue.fromDateTime(billing.date)}');
      sheetObject.appendRow([
        DateTimeCellValue.fromDateTime(billing.date),
        DoubleCellValue(billing.amount.toDouble()),
        TextCellValue(billing.type == BillingType.expense ? 'COST' : 'INCOME'),
        TextCellValue(billing.kind.name),
        TextCellValue(billing.description)
      ]);
    }
    var fileBytes = excel.save();
```
For appendRow method, it works fine. But when I invoke save() method, it will throw exception like this:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: null does not work for DateTimeCellValue
#0      Save._createCell (package:excel/src/save/save_file.dart:142:16)
#1      Save._updateCell (package:excel/src/save/save_file.dart:997:16)
#2      Save._setRows (package:excel/src/save/save_file.dart:652:9)
#3      Save._setSheetElements.<anonymous closure> (package:excel/src/save/save_file.dart:966:7)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#5      Save._setSheetElements (package:excel/src/save/save_file.dart:914:22)
#6      Save._save (package:excel/src/save/save_file.dart:544:5)
#7      Excel.save (package:excel/src/excel.dart:348:21)
It looks like I can not use `DateTimeCellValue` and `DoubleCellValue`. If I use `TextCellValue`, it will not throw exceptions.
@AbhiralJain

**Comment by Epiwish** [comment]
> @Epiwish Hi, If you want to update cell using DateTimeCell value, you need to provide the format using numberFormat parameter in cellStyle.
> 
> Here is an example: sheetObject.updateCell( CellIndex.indexByString('C$i'), DateTimeCellValue( year: 1, month: 1, day: 1, hour: 1, minute: 1, second: 1, ), cellStyle: CellStyle( numberFormat: NumFormat.defaultDate, ), );

How can I set cellStyle when using excel.save()?
I'm just trying to create a new excel file with some DateTimeCellValues

**Comment by sakshitporwal** [comment]
I am getting the same error on DateCellValue, IntCellValue, DoubleCellValue. No matter how i try to implement it.
Something seems to be going wrong in .save() method

**Comment by DucAnh-Vu-Trinh** [comment]
I also get the same error when using excel.save(). Is there any workaround in the meantime?

**Comment by innovatoraakash** [comment]
_updateCell(sheetName, foundRow, columnIndex, rowIndex, data.value,
            data.cellStyle?.numberFormat);

**Comment by ratiger** [comment]
> ```
>    _updateCell(sheetName, foundRow, columnIndex, rowIndex, data.value,
>             data.cellStyle?.numberFormat); 
> ```
> 
> main point of error is from here. If we do not specify the cellStyle it gives format null error and thows exception . I got this error from sheetObject.insertRowIterables() where I can't set any cellstyle If you got problem from same method you can use this fork
> 
> ```
>   excel: 
>     git:
>       url: "https://github.com/innovatoraakash/excel"
> ```
> 
> Giving a default format on this will be productive and easier for everyone.

your update work only for int vaule , but I got error when used datetime, so i eventually used text for my datetime.

**Comment by justkawal** [comment]
Sorry, for issues in this library, I'm doing some structure changes in my local repo and would be releasing soon.
Again sorry for the issues.... I'm trying my best to keep this project alive while searching for the jobs.

Thanks for understanding.
Much appreciated.
