### ISSUE TITLE
excel.delete("Sheet1") execute error

### ISSUE THREAD

**Issue by yeleibo** [justkawal/excel#309]
error info :Cannot remove from an unmodifiable list
![image](https://github.com/justkawal/excel/assets/22091417/cd23a865-af9e-4bfd-a8db-c59df30f3c29)

**Comment by Javicg10** [comment]
I have the same error.

`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Cannot remove from an unmodifiable list
#0      UnmodifiableListMixin.removeWhere (dart:_internal/list.dart:139:5)
#1      Excel.delete (package:excel/src/excel.dart:279:22)
#2      Excel.rename (package:excel/src/excel.dart:213:7)
...
`

I'm seeking advice on whether there's a workaround I can implement, or if this is an issue that needs resolution within the package itself. This functionality is crucial to my application, and any guidance or assistance you can provide would be greatly appreciated.

Thank you for your efforts in maintaining this package!

**Comment by Javicg10** [comment]
The only solution I came with at the moment is to not rename or delete any sheet, which is a pity because I used this to remove the default Sheet1 and now its there.

**Comment by MichiHill1991** [comment]
This is really bad, I need to be able to rename the default sheet or delete it.

**Comment by 17martix** [comment]
I'm having the same issue, can't delete the sheet created by default

**Comment by ksh-b** [comment]
excel.setDefaultSheet can be used as workaround too

**Comment by maboumra** [comment]
Great workarounds by @ksh-b  and @eapCJ . Thank you! The thing is that, even with setDefaultSheet, "Sheet1" remains the second sheet in a more than one sheet scenario. We can live with this but it is annoying.

**Comment by ericsu0630** [comment]
This is strange, it wasn't an issue before. I've been using version 2.1.0 and haven't upgraded dart or flutter either, but now I'm suddenly getting this error.

**Comment by timobaehr** [comment]
Downgrade is not helping me out. I' getting this error as well with version `3.0.0` and even `2.1.0` as well.

**Comment by timobaehr** [comment]
The error is coming from used package `archive`. One fix is to use latest main branch and the newly added deleteFile function.

Link to pull request: https://github.com/justkawal/excel/pull/314

**Comment by mtcahill57** [comment]
Until this is resolved, I was able to fix this by setting the version of **archive** in my own project's pubspec to `3.4.9`. Hope this helps someone

**Comment by maboumra** [comment]
@mtcahill57 it didn't work for me

**Comment by mtcahill57** [comment]
@maboumra 
Hmm, I am able to use it properly. My project's pubspec looks like this:
```
  archive: 3.4.9
  excel: any
```
then I ran `flutter clean; flutter pub get`
