### ISSUE TITLE
[Feature] Add Border functionality 

### ISSUE THREAD

**Issue by SempaiEcchi** [justkawal/excel#32]
Is it possible to keep borders when updating cell values?

**Comment by kawal7415** [comment]
For now Border functionality is not supported yet, Will possibly come in future updates

**Comment by Bes79** [comment]
Interested too

**Comment by corusm** [comment]
Would be interested as well, I could try helping developing

**Comment by Pairs34** [comment]
Are there any plans for this feature?

**Comment by FauconSpartiate** [comment]
> For now Border functionality is not supported yet, Will possibly come in future updates

This is still the latest update...
If you absolutely need it, you can also create a PR implementing it, it would greatly help us 👍

**Comment by FauconSpartiate** [comment]
PR for this feature is open on #220
