### ISSUE TITLE
Read files in Web

### ISSUE THREAD

**Issue by felixwortmann** [justkawal/excel#35]
Since you need the `dart.io` package, which is not really supported in flutter for web, I can not find a way to read excel files that are selected in a browser.

I am using this code to get the file:
```dart
import dart:html;
InputElement uploadInput = FileUploadInputElement();
uploadInput.click();
uploadInput.onChange.listen((final Event event) {
    final File file = uploadInput.files.first;
}
```

**Comment by kawal7415** [comment]
For reading in web, I really don't know for now how to achieve that.

It will be best for you to open up the issue in **flutter's main** repo as they might provide help for this.

**Comment by felixwortmann** [comment]
Reading files in text mode works with that code. You can print it etc. it just somehow does not really work with binary files.

**Comment by venkimurthy07** [comment]
**Getting error:** 
Cannot read property 'Symbol(dartx.forEach)' of null
  at excel.XlsxDecoder.new.[_parseMergedCells] (http://localhost:65001/packages/excel/excel.dart.lib.js:1936:20)


Future<File> selectFile() async {
    InputElement uploadInput = FileUploadInputElement();
    uploadInput.click();

    uploadInput.onChange.listen((e) {
      // read file content as dataURL
      final files = uploadInput.files;
      if (files.length == 1) {
        final file = files[0];
        final reader = new FileReader();

        reader.onLoadEnd.listen((e) {
          // var reade = reader.result as String;
         var excel =  Excel.decodeBytes(reader.result,verify: true);
           print("${excel}");
//          var decoder = SpreadsheetDecoder.decodeBytes(reader.result);
//          var table = decoder.tables['Sheet1'];
//          var values = table.rows[0];
//
//          table.rows.forEach((element) {
//            element.forEach((element1) {
//              print("${element1}");
//              if (element1 == "CateogoryID") {
//                print("first ${element1}");
//              }
//            });
//          });

          return reader.result;
        });

        reader.readAsArrayBuffer(file);
      }
    });
  }

**Comment by arlucio** [comment]
I use flutter_dropzone to get the data and than Excel.decodeBytes to decode it, works perfectly on web!

**Comment by edwinmacalopu** [comment]
you can use filepicker to import excel file https://pub.dev/packages/file_picker

example code:
```
RaisedButton(onPressed: () async {
          FilePickerResult result = await FilePicker.platform.pickFiles(
           type: FileType.custom,
            allowedExtensions: ['xls', 'xlsx'],
            allowMultiple: false);
            if (result != null) {
              var bytes = result.files.single.bytes;
              var excel = Excel.decodeBytes(bytes);

              for (var table in excel.tables.keys) {
                print(table); //sheet Name
                print(excel.tables[table].maxCols);
                print(excel.tables[table].maxRows);
                for (var row in excel.tables[table].rows) {
                  print("$row");
                }
              }
            }
          }
```

**Comment by justkawal** [comment]
I am closing this issue as @edwinmacalopu solutions seems to work.
