### ISSUE TITLE
column size

### ISSUE THREAD

**Issue by mahrmm** [justkawal/excel#41]
Thanks for your hard work.

is there away to control the column's width manually or make it expand to the size of the longest row?

**Comment by kawal7415** [comment]
I will soon start working on that as soon as I complete the on-going flutter projects and flutter game.

For the time being an example file would be helpful to fully understand your needs.

~~ Happy to help

**Comment by mahrmm** [comment]
For example this is how the "comment" column looks like produced by the excel library: 
<img width="987" alt="before" src="https://user-images.githubusercontent.com/3766021/88083262-d59ed580-cb50-11ea-84ce-00e39e7da070.png">

I would like to be able to control "comment" column width (manually or automatically) so i can make it look like this:
<img width="998" alt="after" src="https://user-images.githubusercontent.com/3766021/88083255-d5063f00-cb50-11ea-97c1-ad330df4ed03.png">

Thanks for your effort in advance,

**Comment by kawal7415** [comment]
I thinks that adding the functionality to auto fit column-width will be not possible for now 
as that requires the screen size and rendering functionalities to calculate the size on the go.

But giving the column with manually can be done, and I will try to add the functionality in the upcoming version.

**Comment by mahrmm** [comment]
I will look forward to it.

Thanks!

**Comment by syfulin** [comment]
This will be a very useful feature

**Comment by justkawal** [comment]
hey @mahrmm 
We have started implementing this functionality,
and in the upcoming version you can change the width and height of column and row respectfully.
https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L921

**Comment by mahrmm** [comment]
Thank you so much

**Comment by jawa04** [comment]
is this feature live now ?

**Comment by eliezedeck** [comment]
Updates on this ?

**Comment by dramcio** [comment]
We could connect this issue with:

https://github.com/justkawal/excel/issues/53

Best regards

**Comment by accompagne** [comment]
Hey @justkawal , I know you might not have much free time to work on this project which is super great so far, thanks. However, are you working on this issue? I think this is kind of a blocker to use your package in many use-cases. Thanks in advance!

**Comment by houdayec** [comment]
Hey @justkawal , I know you might not have much free time to work on this project which is super great so far, thanks. However, are you working on this issue? I think this is kind of a blocker to use your package in many use-cases. Thanks in advance!

**Comment by f978gDDfsa** [comment]
> Hey @justkawal , I know you might not have much free time to work on this project which is super great so far, thanks. However, are you working on this issue? I think this is kind of a blocker to use your package in many use-cases. Thanks in advance!

I have the same issue, I have already prepared the pull request #99

**Comment by justkawal** [comment]
@f978gDDfsa Thanks, for the pr Igor

I will review the code and will merge it in a day with other fixes of issues.

**Comment by iCodify** [comment]
Is this live already? I cannot seem to find any such functionality :(

I'm using excel: ^2.0.0-null-safety-3

Love it btw, thx!

**Comment by igdmitrov** [comment]
> Is this live already? I cannot seem to find any such functionality :(
> 
> I'm using excel: ^2.0.0-null-safety-3
> 
> Love it btw, thx!

Try it in your pubspec.yaml:

excel:
    git: 
      url: "git@github.com:justkawal/excel.git"
      ref: "null-safety"

**Comment by iCodify** [comment]
I keep getting 'pub get failed (server unavailable) -- attempting retry' :(

**Comment by igdmitrov** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">

Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/"

**Comment by camsethsum** [comment]
> <img alt="image" width="344" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">
> 
> Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/" or git:

Hi @igdmitrov, I tried to download this but I cant seem to find this in the commits. Justkawal merged this in the null-safety branch but I cant find the merged commit in the null-safety branch under commits. Is there any other way on how to download with your fix included in it? Thank you by the way for this help on Justkawal. This package is really great.

**Comment by igdmitrov** [comment]
> > <img alt="image" width="344" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">
> > Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/" or git:
> 
> Hi @igdmitrov, I tried to download this but I cant seem to find this in the commits. Justkawal merged this in the null-safety branch but I cant find the merged commit in the null-safety branch under commits. Is there any other way on how to download with your fix included in it? Thank you by the way for this help on Justkawal. This package is really great.

Dear @camsethsum I checked it, it works.

My example:
`final sheet = excel[excel.getDefaultSheet() as String];
    sheet.setColWidth(0, 10.0);
    sheet.setColWidth(1, 10.0);
    sheet.setColAutoFit(0);
    sheet.setColAutoFit(1);
    sheet.setColAutoFit(2);
    sheet.setColWidth(50, 10.0);`

`excel:
    git:
      url: "https://github.com/justkawal/excel.git"
      ref: "null-safety"`

**Comment by igdmitrov** [comment]
> > <img alt="image" width="344" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">
> > Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/" or git:
> 
> Hi @igdmitrov, I tried to download this but I cant seem to find this in the commits. Justkawal merged this in the null-safety branch but I cant find the merged commit in the null-safety branch under commits. Is there any other way on how to download with your fix included in it? Thank you by the way for this help on Justkawal. This package is really great.

Dear @camsethsum I checked it, it works.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/75585646/170001150-73047d80-59b2-4541-b957-0a3e118a3295.png">

<img width="451" alt="image" src="https://user-images.githubusercontent.com/75585646/170001218-12e1b427-858f-48b0-95d5-41d786aca219.png">

**Comment by camsethsum** [comment]
> > > <img alt="image" width="344" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">
> > > Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/" or git:
> > 
> > 
> > Hi @igdmitrov, I tried to download this but I cant seem to find this in the commits. Justkawal merged this in the null-safety branch but I cant find the merged commit in the null-safety branch under commits. Is there any other way on how to download with your fix included in it? Thank you by the way for this help on Justkawal. This package is really great.
> 
> Dear @camsethsum I checked it, it works.
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/75585646/170001150-73047d80-59b2-4541-b957-0a3e118a3295.png">
> 
> <img alt="image" width="451" src="https://user-images.githubusercontent.com/75585646/170001218-12e1b427-858f-48b0-95d5-41d786aca219.png">

Hi @igdmitrov, Thank you so much for pointing that out, all this time I didn't know that its already been in the latest null safety version, really my bad. Thank you again.

**Comment by igdmitrov** [comment]
> > > > <img alt="image" width="344" src="https://user-images.githubusercontent.com/75585646/131738966-3d233447-a403-421c-9cd2-981b5c0c5859.png">
> > > > Dear iCodify, I checked it, but it works, you can download this package on your local computer and use it as "path: ../excel/" or git:
> > > 
> > > 
> > > Hi @igdmitrov, I tried to download this but I cant seem to find this in the commits. Justkawal merged this in the null-safety branch but I cant find the merged commit in the null-safety branch under commits. Is there any other way on how to download with your fix included in it? Thank you by the way for this help on Justkawal. This package is really great.
> > 
> > 
> > Dear @camsethsum I checked it, it works.
> > <img alt="image" width="466" src="https://user-images.githubusercontent.com/75585646/170001150-73047d80-59b2-4541-b957-0a3e118a3295.png">
> > <img alt="image" width="451" src="https://user-images.githubusercontent.com/75585646/170001218-12e1b427-858f-48b0-95d5-41d786aca219.png">
> 
> Hi @igdmitrov, Thank you so much for pointing that out, all this time I didn't know that its already been in the latest null safety version, really my bad. Thank you again.

You are welcome!

**Comment by justkawal** [comment]
Sorry for the trouble.
Can you please confirm that are you having this trouble in latest version: `excel: 2.0.1`
If not, please feel free to re-open the issue again.
