### ISSUE TITLE
Reading XLSX file using Viewer

### ISSUE THREAD

**Issue by server2245** [justkawal/excel#46]
Thanks for this great plugin. 
Which plugin do you suggest to read the XLSX file. I am looking to preview XLSX file in my flutter app without losing styles.

**Comment by justkawal** [comment]
> Thanks for this great plugin.
> Which plugin do you suggest to read the XLSX file. I am looking to preview XLSX file in my flutter app without losing styles.

Sorry brother, but for now I can't find any such plugin available for flutter yet,

but u can open this file with other apps like sheet or Microsoft excel if these apps are present on user's device.
