### ISSUE TITLE
Is it possible to print sheet

### ISSUE THREAD

**Issue by kishandonga** [justkawal/excel#48]
Thanks for this great plugin.
can we print the selected sheet with selected print area?

**Comment by justkawal** [comment]
> Thanks for this great plugin.
> can we print the selected sheet with selected print area?

You wants to print the selected range of sheet on to the console/command-line right ?

**Comment by kishandonga** [comment]
Yes your are right as like print area.

**Comment by justkawal** [comment]
Alright @kishandonga ,
Would provide this functionality in the upcoming version.

**Comment by justkawal** [comment]
I think it would be nice to ask these questions on stackoverflow and any issues related to current plugin can be posted here.
