### ISSUE TITLE
No way to insert a row

### ISSUE THREAD

**Issue by JmyW** [justkawal/excel#49]
It's great package, thanks for contribution.
Herein I would like report an issue there is no way to insert a row. Both insertRow and insertRowIterables are failed.
1. insertRow will cause the sheetObject crash, everything behind the index will be gone.
2. insertRowIterables will overwrite the index's row. And on the row, the length is double with same length of "null".

Could you please check it? Or if you need a sample code for reproducing issue, I can make it. Please let me know.

**Comment by nidhinmahesh** [comment]
I think this may help:

use:
`
eachRow(index,row) {
    List<String> dataList = [index.toString()== "null" ? NA :index.toString(), 
                             row['area'] == "null" ? NA : row['area']];
			sheetObject.insertRowIterables(dataList, index+1);}`

call this to populate data in loop:

`maps.asMap().forEach((index,row) => eachRow(index,row));`

**Comment by JmyW** [comment]
Thanks, I tried your way with map conversion but same. It's however added extra several null if use insertRowIterables.

**Comment by justkawal** [comment]
> It's great package, thanks for contribution.
> Herein I would like report an issue there is no way to insert a row. Both insertRow and insertRowIterables are failed.
> 
> 1. insertRow will cause the sheetObject crash, everything behind the index will be gone.
> 2. insertRowIterables will overwrite the index's row. And on the row, the length is double with same length of "null".
> 
> Could you please check it? Or if you need a sample code for reproducing issue, I can make it. Please let me know.

Please provide a code to reproduce the issue.

**Comment by justkawal** [comment]
> It's great package, thanks for contribution.
> Herein I would like report an issue there is no way to insert a row. Both insertRow and insertRowIterables are failed.
> 
> 1. insertRow will cause the sheetObject crash, everything behind the index will be gone.
> 2. insertRowIterables will overwrite the index's row. And on the row, the length is double with same length of "null".
> 
> Could you please check it? Or if you need a sample code for reproducing issue, I can make it. Please let me know.

I have tested the code,
It seems to be working good to me.

I would love to get the code for which u are getting any issue, So that I know that which corner cases I might have missed.
If you would not prefer disclosing it here, then you can mail me on contact@kawal.dev

**Comment by JmyW** [comment]
@justkawal Thanks for support. Please refer the code below:
The code I insert a list with 5 data. But look at the log, it's 5 data + 5 null. And I pressed 3 times, that should be supposedly accumulated three rows but not. 

**[***** Source code as below *****]**
import 'package:flutter/material.dart';
import 'package:excel/excel.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  Excel excel;
  Sheet sheetObject;

  @override
  void initState() {
    super.initState();
    excel = Excel.createExcel();
    sheetObject = excel["sheet1"];
  }

  void _incrementCounter() {
    print("Press Button");
    sheetObject.insertRowIterables(['2020-09-25','A','B','C','D'], 0);

    for (var row in sheetObject.rows) {
      print("length:${row.length} => $row");
    }
  }

  @override
  Widget build(BuildContext context) {
     return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        child: Icon(Icons.add),
      ),
    );
  }
}


**[***** Printed Result as below *****]** 
Restarted application in 1,241ms.
I/flutter (16419): Press Button
I/flutter (16419): length:10 => [2020-09-25, A, B, C, D, null, null, null, null, null]
I/flutter (16419): Press Button
I/flutter (16419): length:10 => [2020-09-25, A, B, C, D, null, null, null, null, null]
I/flutter (16419): Press Button
I/flutter (16419): length:10 => [2020-09-25, A, B, C, D, null, null, null, null, null]

**Comment by justkawal** [comment]
Hey bro,
You are inserting the iterables onto the same row again and again
As you are passing a **0** as rowIndex in ` sheetObject.insertRowIterables(['2020-09-25','A','B','C','D'], 0);`

```dart
  void _incrementCounter() {
    print("Press Button");
    sheetObject.insertRowIterables(['2020-09-25','A','B','C','D'], 0);

    for (var row in sheetObject.rows) {
      print("length:${row.length} => $row");
    }
  }
```

If you want to append the rows one after the another, there is a method named as **appendRow**

```dart
  void _incrementCounter() {
    print("Press Button");
    sheetObject.appendRow(['2020-09-25', 'A', 'B', 'C', 'D']);

    for (var row in sheetObject.rows) {
      print("length:${row.length} => $row");
    }
  }
```
I hope your issue is resolved now !!

**Long Live Open Source**
~Kawal

**Comment by justkawal** [comment]
I thinks there is one issue with null thing it is doubled everytime

I will check on it and will provide an update in a day or two.

**Comment by JmyW** [comment]
Thanks a lot.
Regarding insertRowIterables, I thought I insert a data in row-0, that will shift 0 to 1. I insert again a data to row-0, that will shift 1 to 2, 0 to 1. Isn't it? Thus, you called it "insert", not "update" nor "overwrite". Do I misunderstand?

**Comment by JmyW** [comment]
Hi @justkawal thanks for fixing the issue. Could you teach me how to adopt your fixes in pubspec.yaml file?

**Comment by justkawal** [comment]
By tomorrow, I'll be releasing new version with more features and bugs resolved.

**Comment by JmyW** [comment]
@justkawal Thank you!
I checked the Flutter pub.dev, but there is still 1.1.5. May I know when you will publish to Flutter pub.dev package?
