### ISSUE TITLE
add feature: RTL Sheets

### ISSUE THREAD

**Issue by ammar9191** [justkawal/excel#50]
Hi,
would you mind adding RTL (Right to Left) sheet creating support. although when editing existing RTL sheet name I figured out that it becomes LTR, can you fix this.

**Comment by justkawal** [comment]
Alright @ammar9191 I will look into it as soon as I gets free from password protection functionality.

**Comment by justkawal** [comment]
@ammar9191 Are you having any sample excel file in which its already RTL ?, It would help me to understand much better.

Did u mean to say that the sheet should open in RTL as shown in this website - https://www.extendoffice.com/documents/excel/1763-excel-change-sheet-direction.html ??

**Comment by ammar9191** [comment]
yes exactly the same as the link you provided, please see the sample below:
[report-template.xlsx](https://github.com/justkawal/excel/files/5327660/report-template.xlsx)

**Comment by justkawal** [comment]
alright @ammar9191 

Will look into it and will try to integrate this easily by the end of the week, If it will not **shake** the remaining code

**Comment by justkawal** [comment]
``Given functionality of **RTL (right-to-left)** in this commit``

https://github.com/justkawal/excel/commit/7b6509c5dbf85278382d1496e726971cba082574
