### ISSUE TITLE
change orientation of text

### ISSUE THREAD

**Issue by ArturAntin** [justkawal/excel#51]
is there a way to change the orientation of the text in a cell? basically just rotating it by 90 or 270 degrees.
click [here](https://www.ablebits.com/office-addins-blog/2017/04/26/change-alignment-excel/#changing-text-orientation) if you dont know what i mean.

thanks for the good work!

**Comment by justkawal** [comment]
@ArturAntin you want to rotate the text to some degree ?

Did I got it right ?

**Comment by ArturAntin** [comment]
Yes, correct.

**Comment by justkawal** [comment]
alright @ArturAntin 

Will look into it now,
Thanks for faster responese.

**Comment by ArturAntin** [comment]
hey @justkawal, thanks for adding the rotation-feature! with which update will it be available at pub.dev?

**Comment by justkawal** [comment]
Hey @ArturAntin I will push the new updated version to pub tomorrow with 3 new features including this text-rotation
