### ISSUE TITLE
Change size of a cell

### ISSUE THREAD

**Issue by ArturAntin** [justkawal/excel#53]
hey @justkawal, is it possible to change the size of a single cell? 
So basically changing the width of a specific column and the height of a specific row.

**Comment by justkawal** [comment]
hey @ArturAntin 

In the recent push, we have started implementing the height and width: https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L921

It will take some time, as the new version will have more functionalities.

**Comment by dramcio** [comment]
@justkawal  Any news on this? :)

**Comment by justkawal** [comment]
@dramcio, It might require more time as I'm working on this on week-ends.

**Comment by once10301** [comment]
@justkawal Any news on this? :)

**Comment by f978gDDfsa** [comment]
> @justkawal Any news on this? :)

Prepared the pull request. #99
