### ISSUE TITLE
Saving an Excel file on Web

### ISSUE THREAD

**Issue by JTPenn-EG** [justkawal/excel#54]
I used universal_io as alternative for dart:io
and I used path package to have the join method

```
  static void initExcel(){
    var excel = Excel.createExcel();
    excel.rename("Sheet1", "Andrew");
    excel.encode().then((onValue) {
      File(join("excel.xlsx"))
        ..createSync(recursive: true)
        ..writeAsBytesSync(onValue);
    });
  }
```

The following code produces an error. I imagine it's the use of File...
Docs don't currently have any indication on how to save excels for web...

**Comment by edwinmacalopu** [comment]
I have the same question, any information on how to export the file in flutter web?

**Comment by justkawal** [comment]
I hope it might work for you !!

### Import
```dart
import 'dart:convert';
import 'dart:html' as html;
```

### Code
```dart
excel.encode().then((onValue) {
   final blob = html.Blob([excel bytes]);
   final url = html.Url.createObjectUrlFromBlob(blob);
   final anchor = html.document.createElement('a') as html.AnchorElement
     ..href = url
     ..style.display = 'none'
     ..download = 'excel_file_name.xlsx';
   html.document.body.children.add(anchor);

   // download the file
   anchor.click();
 });

// cleanup
// html.document.body.children.remove(anchor);
// html.Url.revokeObjectUrl(url);
```

Do let me know, if this works out for you ??

**Comment by edwinmacalopu** [comment]
> I hope this might work for you !!
> 
> ### Import
> ```dart
> import 'dart:convert';
> import 'dart:html' as html;
> ```
> 
> ### Code
> ```dart
> excel.encode().then((onValue) {
>    final blob = html.Blob([excel bytes]);
>    final url = html.Url.createObjectUrlFromBlob(blob);
>    final anchor = html.document.createElement('a') as html.AnchorElement
>      ..href = url
>      ..style.display = 'none'
>      ..download = 'excel_file_name.xlsx';
>    html.document.body.children.add(anchor);
> 
>    // download the file
>    anchor.click();
> 
>    // cleanup
>    // html.document.body.children.remove(anchor);
>    // html.Url.revokeObjectUrl(url);
>  });
> ```
> 
> Do let me know, if this works out for you ??

If it wasn't too much trouble, could you show a small example of how to convert excel to bytes?

**Comment by chetan2914** [comment]
> ```dart
> import 'dart:convert';
> import 'dart:html' as html;
> ```

thank you it worked for me....

**Comment by justkawal** [comment]
> > I hope this might work for you !!
> > ### Import
> > ```dart
> > import 'dart:convert';
> > import 'dart:html' as html;
> > ```
> > 
> > 
> > ### Code
> > ```dart
> > excel.encode().then((onValue) {
> >    final blob = html.Blob([excel bytes]);
> >    final url = html.Url.createObjectUrlFromBlob(blob);
> >    final anchor = html.document.createElement('a') as html.AnchorElement
> >      ..href = url
> >      ..style.display = 'none'
> >      ..download = 'excel_file_name.xlsx';
> >    html.document.body.children.add(anchor);
> > 
> >    // download the file
> >    anchor.click();
> > 
> >    // cleanup
> >    // html.document.body.children.remove(anchor);
> >    // html.Url.revokeObjectUrl(url);
> >  });
> > ```
> > 
> > 
> > Do let me know, if this works out for you ??
> 
> If it wasn't too much trouble, could you show a small example of how to convert excel to bytes?

your **onValue** is **excelBytes**.

**Comment by chetan2914** [comment]
Thank you bro it worked for me....

**Comment by wahyu-handayani** [comment]
Thank you so much @justkawal it helps me

**Comment by justkawal** [comment]
> Thank you so much @justkawal it helps me

Anytime ✌️🥳

**Comment by adadion** [comment]
Hi Kawal, above solution works for me while in flutter web debug mode, but when I do run `flutter build web`, the file extension were overwritten into txt. For example:

`excel.encode().then((onValue) {
   final blob = html.Blob([excel bytes]);
   final url = html.Url.createObjectUrlFromBlob(blob);
   final anchor = html.document.createElement('a') as html.AnchorElement
     ..href = url
     ..style.display = 'none'
     ..download = 'report.xlsx';
   html.document.body.children.add(anchor);

   // download the file
   anchor.click();

   // cleanup
   // html.document.body.children.remove(anchor);
   // html.Url.revokeObjectUrl(url);
 });`

It will create file named report.txt. While on debug mode, it successfully create file named report.xlsx.
Any clue?

**Comment by adadion** [comment]
Never mind, it seems my Chrome extension Chrono Download Manager overwrite those file extension.
It works in debug mode because the Chrome window didn't come with any extension.
