### ISSUE TITLE
sourceRegx never assigned when source.runtimeType is RegExp in findAndReplace method

### ISSUE THREAD

**Issue by KernelPanic92** [justkawal/excel#55]
https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L1032

**Comment by justkawal** [comment]
@KernelPanic92 Yeah that's a Buggy code.

Thanks again @KernelPanic92

**Comment by KernelPanic92** [comment]
You're so welcome! 🦅
