### ISSUE TITLE
findAndReplace not working 

### ISSUE THREAD

**Issue by KernelPanic92** [justkawal/excel#56]
https://github.com/justkawal/excel/blob/7fd12752b179fc6b5e8e06f678950b71f6eb2133/lib/src/sheet/sheet.dart#L1048

missing a '.value' in chain 'sourceRegx.hasMatch(this._sheetData[i][j].toString())'

**Comment by justkawal** [comment]
@KernelPanic92 Awesome brother,
You got eagle's eye,
Thank You. I will correct it and will push it in the coming version with formula functionality.

**Comment by KernelPanic92** [comment]
I'm glad to be of help! 👀

**Comment by qcks** [comment]
bug
 int replacedCount = sheetObject.findAndReplace('Flutter', 'Google');

replacedCount = 0;
