### ISSUE TITLE
How to get a range of cells

### ISSUE THREAD

**Issue by issahaku-max** [justkawal/excel#59]

**Comment by ArinFaraj** [comment]
I'm planning to make a pr here is the current progress 
use it like this
```dart
var data = selectRange(mySheet, 'D8:H12');
```
```dart
List<List<dynamic>> selectRangeWithString(Sheet sheet, String range) {
  var rangeVars = range.split(':');

  CellIndex from = CellIndex.indexByString(rangeVars[0]);
  CellIndex to = CellIndex.indexByString(rangeVars[1]);

  return selectRange(sheet, from, to);
}

List<List<dynamic>> selectRange(Sheet sheet, CellIndex from, CellIndex to) {
  List<List<dynamic>> selectedRange = List<List<dynamic>>();

  for (var row in sheet.rows.sublist(from.rowIndex, to.rowIndex + 1)) {
    var selectedColumn = row.sublist(from.columnIndex, to.columnIndex + 1);
    selectedRange.add(selectedColumn);
  }

  return selectedRange;
}
```


also, mine returns the values of the cells, there is a method in the package that is not completed and returns an empty list
but it plans to return as a list of cell Data which seems to be a better idea but uses more resources than needed if you just want to get the values 

```dart 
sheet.getSelection(CellIndex.indexByString('A1'),end: CellIndex.indexByString('C1'));
```

**Comment by issahaku-max** [comment]
thank you alot....you saved my ass😘😘😘

**Comment by justkawal** [comment]
> I'm planning to make a pr here is the current progress
> use it like this
> 
> ```dart
> var data = selectRange(mySheet, 'D8:H12');
> ```
> 
> ```dart
> List<List<dynamic>> selectRangeWithString(Sheet sheet, String range) {
>   var rangeVars = range.split(':');
> 
>   CellIndex from = CellIndex.indexByString(rangeVars[0]);
>   CellIndex to = CellIndex.indexByString(rangeVars[1]);
> 
>   return selectRange(sheet, from, to);
> }
> 
> List<List<dynamic>> selectRange(Sheet sheet, CellIndex from, CellIndex to) {
>   List<List<dynamic>> selectedRange = List<List<dynamic>>();
> 
>   for (var row in sheet.rows.sublist(from.rowIndex, to.rowIndex + 1)) {
>     var selectedColumn = row.sublist(from.columnIndex, to.columnIndex + 1);
>     selectedRange.add(selectedColumn);
>   }
> 
>   return selectedRange;
> }
> ```
> 
> also, mine returns the values of the cells, there is a method in the package that is not completed and returns an empty list
> but it plans to return as a list of cell Data which seems to be a better idea but uses more resources than needed if you just want to get the values
> 
> ```dart
> sheet.getSelection(CellIndex.indexByString('A1'),end: CellIndex.indexByString('C1'));
> ```

It's awesome work friend.

Would be waiting for your pr.

Lpng Live 🔥pen Source
