### ISSUE TITLE
flutter: Bad state: No element

### ISSUE THREAD

**Issue by ArielFerreiro** [justkawal/excel#61]
The plugin is raising this error (Bad state: No element) when executing the decode methond -> Excel.decodeBytes(bytes);

I can open the excel file perfectly in my PC but loading it from the assets raises this issue.

**Comment by justkawal** [comment]
Can you please post the error log ?

**Comment by justkawal** [comment]
@ArielFerreiro As it's seems that your error might be resolved, as we didn't hear from you.

Feel free to reopen the issue, if you finds any trouble.

Don't forget to become a Patreon member.
Long Live Open Source

**Comment by ArielFerreiro** [comment]
Hi Singh (@justkawal) sorry I was on vacations and still a bit on it. The thing is in the file itself I think, as excel is opening it but before raises a warning telling me that will try to recover the data and finally it opens it correctly. So I guess it is something with the file itself. I will try to check it with my backend colleagues and in case come back.
