### ISSUE TITLE
Export in web 

### ISSUE THREAD

**Issue by AHoxha19** [justkawal/excel#67]
Is there a way to export the file in Web version? I tried but it seems that there is no way to download the file in downloads folder for example.

**Comment by justkawal** [comment]
Have a look at : https://github.com/justkawal/excel#saving-file-in-flutter-web

Don't forget to become a patron member, if this helped you.

Thanks Again
Long Live Open Source

**Comment by AHoxha19** [comment]
Thanks for your answers ! I think you need to update the package in pub.dev so that i can use the save method you added.

**Comment by justkawal** [comment]
@AHoxha19 
Sure, y not I'll update the package in the pub.dev in the coming week as Excel had some improvements and also new features and functionalities. 
The main optimization is based on issue: #73 

So I am waiting to make it stable and bug free.

Thanks.
Long Live 🔥pen Source

**Comment by AHoxha19** [comment]
No problem you did an incredible job thanks, keep going !
