### ISSUE TITLE
Share excel file

### ISSUE THREAD

**Issue by matheusresende7** [justkawal/excel#71]
Could you add share excel file option in this package, please?

**Comment by justkawal** [comment]
@matheusresende7 Thanks for the issue,

**There are a lot of great plugins out there which are best at it's sharing functionality**

  - If you have `exported the file` and wants to share it then use: [Share](https://pub.dev/packages/share)

  - But for `directly sharing the bytes` got as a result from `encode` function then use: [esys_flutter_share](https://pub.dev/packages/esys_flutter_share).
  In `esys_flutter_share` there is a function which accepts bytes but I didn't have gone through its implementation. 

I hope that you finds it easy to use these plugins.

Thanks again,
Long Live Open Source
