### ISSUE TITLE
too much time to generate large files

### ISSUE THREAD

**Issue by GnRSlash** [justkawal/excel#73]
Hi everyone, first of all I need to say thanks to share this library with us.

I have two questions:
First: How can I change CellType?  I mean, I have a number like this: 00037198765 and I want this to be String, not number.

Second: I am generating a 9000 rows by 8 columns with data (only string data, no formating), and it is impossible because library consume too much time to generate and encode...   generate part took me more than 7 minutes!
This is the result of time spent:
Generating executed in 0:07:22.328475
Encoding executed in 0:24:20.345250
Downloaded executed in 0:00:00.047855

I have another project exporting the same data but using excel xml files, and it is very fast, about 5 seconds.
The file size of your lib is 570Kb and total time is 32 minutes
The file size of xml is 12Mb and total time is 5 seconds

Am I doing something wrong?

Here is the test project that I used:
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Stopwatch stopwatch = new Stopwatch()..start();

            Excel excel = Excel.createExcel();
            Sheet sh = excel['Sheet1'];
            for (int i = 0; i < 8; i++) {
              sh.cell(CellIndex.indexByColumnRow(rowIndex: 0, columnIndex: i))
                  .value = 'Col $i';
              sh.cell(CellIndex.indexByColumnRow(rowIndex: 0, columnIndex: i))
                  .cellStyle = CellStyle(bold: true);
            }
            for (int row = 1; row < 9000; row++) {
              for (int col = 0; col < 9; col++) {
                sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ${row}_$col';
              }
            }
            print('Generating executed in ${stopwatch.elapsed}');
            stopwatch.reset();
            excel.encode().then((onValue) {
              print('Encoding executed in ${stopwatch.elapsed}');
              stopwatch.reset();
              downloadFile(onValue, 'excel_test.xlsx');
              print('Downloaded executed in ${stopwatch.elapsed}');
            });
          },
          child: Text('Export'),
        ),
      ),
    );
  }

  void downloadFile(List<int> bytes, String downloadName) {
    // Encode our file in base64
    final _base64 = base64Encode(bytes);
    // Create the link with the file
    final anchor =
    AnchorElement(href: 'data:application/octet-stream;base64,$_base64')
      ..target = 'blank'
      ..setAttribute('download', downloadName);
    // add the name
    //anchor.download = downloadName;
    // trigger download
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    return;
  }
```

**Comment by justkawal** [comment]
@GnRSlash Firstly thanks for throwing light on this issue.

I have ran tests and found out something which u might have missed !!

In your code make this change and see the magic, 
#### `Now you will see that It is not excel library taking time`, It is` Dart` which is `taking time in String concatenation`.

## Change this code:
```dart
sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ${row}_$col';
```
## to:

```dart

// this is will take milliseconds generation time I think so As per my tests.
sh.cell(CellIndex.indexByColumnRow(columnIndex: col, rowIndex: row))
                    .value = 'value ';

```

### Surprised right ??
`So now I thinks you know that this is from dart side that why string concatenation is taking too much time ?`
`You can post this same issue on the dart-sdk side.`

Secondly, I will surely look into the excel generation part that why it is taking too much time !!

**Comment by justkawal** [comment]
@GnRSlash 

Hey, Sorry for delays, Actually admitted in hospital due to Covid-19.

Will push the change whenever I'll reach home.

Please Stay Healthy and Stay Safe.
Regularly wash your hands.

Thanks,
Long Live 🔥pen Source

**Comment by GnRSlash** [comment]
Hi,
I want to share with you what they said about this time consuming

[https://github.com/dart-lang/sdk/issues/44776](url)

Hope this can help you to improve your library to work with larger data.
Thank you again

**Comment by justkawal** [comment]
> Hi,
> I want to share with you what they said about this time consuming
> 
> [https://github.com/dart-lang/sdk/issues/44776](url)
> 
> Hope this can help you to improve your library to work with larger data.
> Thank you again

Yeah I have looked at the conversation, I will look into optimisation on excel.

**Comment by pisabev** [comment]
I think the slow behaviour comes from "_findRowByIndex". When you generate xls file from builk data this method exponentially slows down as the number of nodes (rows) gets bigger and bigger. Maybe passing some flag when you call "encode" to skip checking for rows/cells and just create new ones would be a good step....

**Comment by justkawal** [comment]
@GnRSlash 
I've run some tests and looks good to me now as it is doing processing faster than before.

Would you please check it ? and let me know how this performs on your side ??

**Comment by GnRSlash** [comment]
@justkawal ,

I can't test it now, but i'll do it as soon as possible. Today is 15/02, maybe I'll test it on 18/02 at work.
Thank you!

**Comment by GnRSlash** [comment]
Hi,

I spent a little to figure out how to use excel as git/commit dependency and did it this way:

The results was:
Generating executed in 0:00:00.655229
Encoding executed in 0:00:09.619265
Downloaded executed in 0:00:00.065425

File size was: 574 kB


I think you did a very good job and now your library is very good to use with larger files!!!!
Congratulations and thank you again!!

**Comment by justkawal** [comment]
@GnRSlash
I've run some tests and looks good to me now.
Thanks for pointing out the bug, that's what open source is for.

Let me know, if this works on your side ??

~ Best
~ Kawaljeet Singh

**Comment by GnRSlash** [comment]
> @GnRSlash
> I've run some tests and looks good to me now.
> **Thanks for pointing out the bug, that's what open source is for.**
> 
> Let me know, if this works on your side ??
> **You got Eagle's eye, you finds out something to be corrected. (Thanks for your contribution to this library in improving it.)**
> 
> ~ Best
> ~ Kawaljeet Singh

Sorry but, did you make a new commit to test?
Anyway, when do you pretend to do a new official update (1.1.6)  ?

Thank you!

**Comment by justkawal** [comment]
@GnRSlash 
Before March starting, A new version will be released.

Btw, you can test the new version from the latest commit @GnRSlash .

Once it runs on your side, inform me if possible !

~ Best
~ Kawaljeet Singh

**Comment by GnRSlash** [comment]
Sorry, I was trying to identify the commit, it was difficult, but I found it and everything is fine now. I ran the tests again and it looks great!

Thank you for your efforts!

**Comment by justkawal** [comment]
@GnRSlash 
Thanks for giving your contribution to flutter - excel
