### ISSUE TITLE
Since a resent update of sdk I can't use excel package

### ISSUE THREAD

**Issue by MarrouDamien** [justkawal/excel#75]
Debug Console ouput:
Because every version of integration_test from sdk depends on archive 3.0.0-nullsafety.0 and excel 1.1.5 depends on archive ^2.0.0, integration_test from sdk is incompatible with excel 1.1.5.

**Comment by justkawal** [comment]
### Solved
Try below steps:

1) Open project folder and remove **excel** dependency
2) Add these lines in your project's pubspec.yaml
```
dependency_overrides:
  archive : ^2.0.0
```
after adding it will look like:
```
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  archive : ^2.0.0
```
3) run `flutter clean` in the project folder.
4) Close project folder
5) Open terminal and run below commands :
      > `flutter upgrade`

      > `pub cache repair`

      > `flutter update-packages --force-upgrade`

6) Open project folder and add the dependency `excel:

_**Tell me if this works ?**_

**We celebrate every issue as it helps us to improve.**
~Thank You
LONG LIVE OPEN S🔥URCE
