### ISSUE TITLE
Excel manipulation in flutter web

### ISSUE THREAD

**Issue by udayaraj5193** [justkawal/excel#76]
Hi Great work guys, I'm not able to use this package in flutter web due to dart.io will not work in flutter web, how we can use export   to excel from flutter web with multiple sheets.

Thanks in advance.

**Comment by justkawal** [comment]
https://github.com/justkawal/excel/blob/b43e587796b7d0f45450b9e81f584eca76b03dc1/lib/src/excel.dart#L297

This has been **resolved** in the recent push.
As soon as it becomes stable it will be available on **https://pub.dev/packages/excel**
