### ISSUE TITLE
I think you mean insertRow(82) in Readme

### ISSUE THREAD

**Issue by vadrian89** [justkawal/excel#77]
Hello,
Looking at the documentation something struck me.

// insert row at index = 82
sheetObject.removeRow(82);

Guessing you mean insertRow(82)?

Thank you for the package, in advance. Reading a bit through it as I want to use it in a project of mine.

**Comment by WilliBobadilla** [comment]
yes, he just was wrong, things that happens! excelent package!

**Comment by justkawal** [comment]
@vadrian89 
Sorry for late reply, Was stuck in this covid,

Thanks for pointing it out, I'll update the ReadMe in a second,

Excel's null-safety version is under development and you are about to see some major performance boosts.
