### ISSUE TITLE
excel.save() method seems unavailable

### ISSUE THREAD

**Issue by joris1995** [justkawal/excel#78]
First of all, thanks for providing this extremely convenient piece of software for free here.

Everything seems to work fine, yet I find myself unable to export a generated document. In the [documentation](https://github.com/justkawal/excel#saving), it says that I should be able to call save() on an excel document, but this method seems unavailable. 

In my pubsbec.yaml I'm using ^1.1.5. My code looks like this:

```
   var excel = Excel.createExcel();
    excel.rename('Sheet1', 'Excel test');

    Sheet sheet = excel['ExcelTest'];

    // Setup Top bar
    var titleCell = sheet.cell(CellIndex.indexByString('A1'));
    // More logic to setup the Top Bar

    // Add data
    for (var i = 0; i < data; i ++) {
      CampaignRecord record = campaigns[i];

      // Logic that sets data in the right column and row
    }

    // Save
    var data = await excel.save(); // UNAVAILABLE
```

I now implemented [this](https://github.com/justkawal/excel/issues/67#issuecomment-780621109) solution, but when I try to open the document it generates, Excel says it's damaged and it shows data in the wrong cells. 

What am I missing?

**Comment by justkawal** [comment]
@joris1995 
Please give me 1 to 2 days, I'll update the latest stable version on the pub.dev.

~ Best
~ Long Live 🔥pen Source

**Comment by joris1995** [comment]
@justkawal Perfect! Thank you so much 🤩

**Comment by justkawal** [comment]
@joris1995 
Anytime ✌️✌️

**Comment by joris1995** [comment]
Hi, just checking in, Do you have any update on when a patch including the .save() method will be available?

**Comment by vsmmart** [comment]
Hey joris1995, I've used encode() instead of save(). Maybe this helps.

`excel.encode().then((fileBytes) async {
      Future<Directory> _getDownloadsPath =
          DownloadsPathProvider.downloadsDirectory;
      var downloadsDir = await _getDownloadsPath;
      var dowloadsPath = downloadsDir.path;
      File(join("$dowloadsPath/test_wrap.xlsx"))
        ..createSync(recursive: true)
        ..writeAsBytesSync(fileBytes);`

**Comment by joris1995** [comment]
Works like a charm! Thanks

**Comment by surveshoeb** [comment]
@justkawal till when we can expect the **save** function?

**Comment by justkawal** [comment]
@surveshoeb The save function will be available by the end of the month. in Null-safe and non null-safe version.
