### ISSUE TITLE
rtl not found !

### ISSUE THREAD

**Issue by MostafaOsama99** [justkawal/excel#84]
I have installed the last version  excel:^1.1.5, and I followed the documentation to make the excel sheet rtl.
but it says that rtl isn't defined. is this feature available or not?

Also it takes too much time to save the file (excel.encode) , (i was saving a file contains around 4000 row, and it takes around 6 minutes)

**Comment by justkawal** [comment]
@MostafaOsama99 

If you are using the non null-safe version then the function will be available by the end fo this week,

But in the null-safe version the **RTL** functionality and other features are available.

**Comment by MostafaOsama99** [comment]
@justkawal thanks for response, I have found it in 'SheetObject' named 'isRTL', i have set it to true but the generated excel is LTR also

**Comment by justkawal** [comment]
Are you using non null-safe version ??

**Comment by MostafaOsama99** [comment]
yes, I have found it in null-saftey version, it's called 'isRTL' in
'SheetObject'. However, the generated sheet was LTR also

**Comment by justkawal** [comment]
@MostafaOsama99 I'll have a look on it as soon as possible.
