### ISSUE TITLE
how to implement this library in web

### ISSUE THREAD

**Issue by aharoldk** [justkawal/excel#86]
i already try this library, but i confused to use it in web.

could anyone help me?

**Comment by nishuthan** [comment]
To save a file in flutter web use the code below 

`
Excel excel = Excel.createExcel();
 final sheetTxns = excel['Sheet 1']; //do whatever operation you wish to do
 if (kIsWeb){
excel.save(fileName: outputFile);//saves the file (automatic download)
}else{
// use path provider and dart.io to save file
}`

Note: use Null safety version `excel: ^2.0.0-null-safety` This version only has the save function

**Comment by justkawal** [comment]
@aharoldk Code by @nishuthan will work for you.

For more info head to: https://github.com/justkawal/excel#saving
