### ISSUE TITLE
Problem to use more than 1 xslx files ... keep the preview data on files

### ISSUE THREAD

**Issue by JERV-code** [justkawal/excel#88]
I'm using Prerelease: 2.0.0-null-safety and getting local asset

I try to use exactly this code but can't find the property update on decodeBytes function that you use on your code, without this property it works but keep the data of last file.

    
    import 'package:flutter/services.dart' show ByteData, rootBundle;
    
    
               ByteData data = await rootBundle.load("assets/existing_excel_file.xlsx");
               var bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  --- >    var excel = Excel.decodeBytes(bytes, update: true);                                               (no property update found)
        
    how can I update the data ? ... can you help me please

**Comment by justkawal** [comment]
@JERV-code 
Actually the readme was not updated !! Thanks for pointing it out.

You are good to go without the update parameter.
```
var excel = Excel.decodeBytes(bytes);
```

Thanks.

**Comment by justkawal** [comment]
If you still finds any difficulty then reopen this issue right-away.

**Comment by JERV-code** [comment]
my problem is't related with the property update ... I'm using multiple xlsx files and just the first one is loaded, the otrer information there isn't readed from the file.

this just happend to me on 2.0.0-null-safety version 

share wiith you my flutter doctor maybe some version there is related with my problem

[✓] Flutter (Channel master, 2.2.0-11.0.pre.103, on Mac OS X 10.15.7 19H524 darwin-x64, locale es-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)

thanks for your help!

**Comment by justkawal** [comment]
@JERV-code
try running this command in your command line one by one

/// To make sure you are on the stable branch of flutter
```sh
flutter channel stable
flutter upgrade
flutter doctor -v
flutter pub cache repair
flutter doctor -v
```

and then try using the excel plugin, I hope your project is in null-safety too.

for reading multiple: ( just read the file in multiple object );

```

var file_1_bytes = await readAssetFile("assets/existing_excel_file_1.xlsx");
var excel_file_1 = Excel.decodeBytes(file_1_bytes);

var file_2_bytes = await readAssetFile("assets/existing_excel_file_2.xlsx");
var excel_file_2 = Excel.decodeBytes(file_2_bytes);

Future<Uint8List> readAssetFile(String path) async {
    ByteData data = await rootBundle.load(path);
    var bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    return bytes;
}

```

**Comment by JERV-code** [comment]
I try all this commands but they don't works for me 

I also am using every xlsx like diferent object ... in the version 1.1.5 all was fine to me, i did't change nothing in my code 

and this version (1.1.5)  have incompatibility when i use pub get on  my pubspec.yaml, so i dont know what can i do

**Comment by ashishbeck** [comment]
I am having the same issue. I will elaborate on my case.

I open `file1.xlsx` using `var excel = Excel.decodeBytes()`. I update cell "A1". I use `excel.encode()` and save the bytes into a file and share it outside the app using the share plugin.
Then I open `file2.xlsx` using the same object `var excel = Excel.decodeBytes()`. The cell "A1" is the same as the one from `file1.xlsx`. The `excel` object is not updated with the new data.

**Comment by justkawal** [comment]
@ashishbeck 
This issue is coming in the new null-safe version right ??

**Comment by justkawal** [comment]
@ashishbeck && @JERV-code 

It's fixed now in version:
```
excel: 2.0.0-null-safety-1
```

https://pub.dev/packages/excel/versions/2.0.0-null-safety-1

Inform me if this works out for you !!

**Comment by JERV-code** [comment]
no, it does't work yet, I update my puspec with new commit but not works ... if there are some that i can do to solve this let me know please, thanks !

**Comment by justkawal** [comment]
@JERV-code 
Can you please show an example code ?

**Comment by ashishbeck** [comment]
I have prepared a minimal code snippet from my project here. You need these packages to run it
```
  path_provider: ^2.0.1
  file_picker: ^3.0.1
  permission_handler: ^7.0.0
  excel: ^2.0.0-null-safety-1
  share: ^2.0.1
```
And this is a basic page that should demonstrate the problem. 
Open a file. Make some changes. Share it. Reopen the file (or a different file too).
```
import 'package:share/share.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:excel/excel.dart';
import 'package:permission_handler/permission_handler.dart';

class Temp extends StatefulWidget {
  @override
  _TempState createState() => _TempState();
}

class _TempState extends State<Temp> {
  Excel excel;

  Future openFile() async {
    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['xlsx'],
    ).catchError((onError) {
      print(onError);
      openAppSettings();
    });
    if (result != null) {
      PlatformFile file = result.files.first;
      var bytes = await File(file.path).readAsBytes();
      setState(() {
        excel = new Excel.decodeBytes(bytes);
      });
    }
  }

  Future shareFile() async {
    String path;
    var bytes = excel.encode();
    Directory appDocDir = await getApplicationDocumentsDirectory();
    path = appDocDir.path + '/file.xlsx';
    File(path).writeAsBytes(bytes);
    Share.shareFiles([path]).then((value) => setState(() => excel = null));
  }

  @override
  Widget build(BuildContext context) {
    Widget button(String label, Function onPressed) => TextButton(onPressed: onPressed, child: Text(label));

    if (excel != null) {
      Sheet sheet = excel.sheets.values.first;
      CellIndex index = CellIndex.indexByColumnRow(rowIndex: 0, columnIndex: 0);
      Data cellData = sheet.cell(index);

      Widget textField() => TextFormField(
            initialValue: cellData.value,
            onChanged: (val) => setState(() {
              cellData.value = val;
            }),
          );

      return Scaffold(
          body: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [textField(), button('Open New', openFile), button('Share', shareFile)]));
    }
    return Scaffold(
        body: Center(child: button('Open New', openFile)));
  }
}
```

**Comment by justkawal** [comment]
@ashishbeck 
Can you please try to use:
```
excel: 2.0.0-null-safety-1
```

On my side it looks good without any errors.

**Comment by ashishbeck** [comment]
I am using the latest version. If you open a .xlsx file and then perform `.encode()` on it and repeat this process for different .xlsx files several times, you will end up with a very weird combination of all the files. Please try it and let me know if you get what I am saying. Thanks

**Comment by JERV-code** [comment]
off course this is a function to get a version and model car: 

modelo = '';
version = '';

  Future _getModelo (String fielName) async {

    ByteData data = await rootBundle.load("assets/config/$fielName.xlsx");
    var bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    var excel = Excel.decodeBytes(bytes,);

    int versionParcial;
    
    try {
      versionParcial = int.parse(version.toString());
    } catch (er){
      print('~~~~~~~~~ ---- > la version de este vehiculo no es un numero');
    }

    int position = excel[marca].rows[0].indexOf(versionParcial != null ? versionParcial : version);

    modelo = excel[marca].rows[2][position].value.toString();

    try {
      final double parcial = double.parse(modelo);
      modelo  = parcial.round().toString();
    } catch (er) {
      print('~~~~~~~~~~~~~~~ -----> la variable modelo no es un valor numerivo');
    }

  }

**Comment by justkawal** [comment]
> I am using the latest version. If you open a .xlsx file and then perform `.encode()` on it and repeat this process for different .xlsx files several times, you will end up with a very weird combination of all the files. You can use the sample code that I posted earlier and share the final file outside of the app and open it externally to check. Please try it and let me know if you get what I am saying. Thanks



@ashishbeck 

I was unable to track down the issue on my side !! as I clearly see the variables being initialised again and again every time for the new excel files.

Please have a look at the changed and correct sample code as your were not waiting on the async functions and also go with latest version of excel.

pubspec:
```
  path_provider: ^2.0.1
  file_picker: ^3.0.1
  permission_handler: ^7.0.0
  excel: ^2.0.0-null-safety-2 # this is the latest version for null-safety
  share: ^2.0.1
```

Corrected code:
```
import 'package:share/share.dart';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:excel/excel.dart';
import 'package:permission_handler/permission_handler.dart';

class Temp extends StatefulWidget {
  @override
  _TempState createState() => _TempState();
}

class _TempState extends State<Temp> {
  Excel excel;

  Future openFile() async {
    FilePickerResult result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['xlsx'],
    ).catchError((onError) {
      print(onError);
      openAppSettings();
    });
    if (result != null) {
      PlatformFile file = result.files.first;
      var bytes = await File(file.path).readAsBytes();
      setState(() {
        excel = new Excel.decodeBytes(bytes);
      });
    }
  }

  Future shareFile() async {
    String path;
    var bytes = excel.encode();
    Directory appDocDir = await getApplicationDocumentsDirectory();
    path = appDocDir.path + '/file.xlsx';

    /// this has to be awaited 🤔 
    await File(path).writeAsBytes(bytes);

    /// this has to be awaited 🤔 
    await Share.shareFiles([path]).then((value) => setState(() => excel = null));
  }

  @override
  Widget build(BuildContext context) {
    Widget button(String label, Function onPressed) => TextButton(onPressed: onPressed, child: Text(label));

    if (excel != null) {
      Sheet sheet = excel.sheets.values.first;
      CellIndex index = CellIndex.indexByColumnRow(rowIndex: 0, columnIndex: 0);
      Data cellData = sheet.cell(index);

      Widget textField() => TextFormField(
            initialValue: cellData.value.toString(),
            onChanged: (val) => setState(() {
              cellData.value = val;
            }),
          );

      return Scaffold(
          body: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [Text(cellData.value.toString()), textField(), button('Open New', openFile), button('Share', shareFile)]));
    }
    return Scaffold(
        body: Center(child: button('Open New', openFile)));
  }
}
```

**Comment by ashishbeck** [comment]
The latest version `excel: ^2.0.0-null-safety-3` has fixed the issue for me. Thanks a lot!

**Comment by justkawal** [comment]
@ashishbeck Anytime

**Comment by JERV-code** [comment]
for me too, thank you so much!
