### ISSUE TITLE
After cloning a sheet both sheets are modified instead of only the second one

### ISSUE THREAD

**Issue by timobaehrNexplore** [justkawal/excel#89]
Hi, I'm trying to create a second sheet (what works):

```dart
final excel = Excel.createExcel();

final Sheet sheet1 = excel.sheets['Sheet1'];
sheet1.cell(CellIndex.indexByString('A1'))
      ..value = '1';

excel.copy('Sheet1', 'Sheet2');
final sheet2 = excel.sheets['Sheet2'];
sheet2.cell(CellIndex.indexByString('A1'))
      ..value = '2';
```

Unfortunately Sheet1 and Sheet2 now does have value '2' written inside A1. So value of Sheet1 is overridden. What is my fault or how can I fix this? Using `unLink` or `link` didn't help.

**Comment by justkawal** [comment]
@timobaehrNexplore 
You are using null-safe version or non null-safe ??

**Comment by justkawal** [comment]
@timobaehrNexplore 

It's fixed now in version:
```
excel: 2.0.0-null-safety-1
```

Inform me if this works out for you !!

**Comment by timobaehrNexplore** [comment]
Thank you, great!

**Comment by justkawal** [comment]
@timobaehrNexplore

For more good fixes use:
```
excel: 2.0.0-null-safety-2
```
