### ISSUE TITLE
New data of Excel have been cache data of previous file

### ISSUE THREAD

**Issue by tinhpt38** [justkawal/excel#91]
Steps:
1. Select File with name is ABC.xlsx;
2. Read data of ABC.xlsx;
3. Select File with name is EF.xlsx;
4. The data of EF.xlsx is data of ABC.xlsx

My code: 

importExcel(File? file) async {
    List<User> newUsrs = [];
    try {
      var bytes = file!.readAsBytesSync();
      var excel = Excel.decodeBytes(bytes);

      for (var table in excel.tables.keys) {
        excel.removeRow(table, 0);
        List<List<Data?>> rows = excel.tables[table]!.rows;
        for (var row in rows) {
          if (row[0] == null) {
            continue;
          }
          Data? username = row[1];
          Data? lastname = row[2];
          Data? firstname = row[3];
          Data? genty = row[4];
          Data? birthday = row[5];
          Data? wasborn = row[6];
          double? score;
          if (row.length > 7) {
            Data? scoreData = row[7];
            if (scoreData != null) {
              score = double.tryParse(scoreData.value.toString());
            } else {
              score = null;
            }
          }

          newUsrs.add(User(
              username: username?.value,
              fullName: lastname?.value + " " + firstname?.value,
              genty: genty?.value,
              birthday: birthday?.value,
              wasborn: wasborn?.value,
              defaultScore: score));
        }
      }
      return newUsrs;
    } catch (_) {
      setStatus(create: false, success: false, fail: true);
    }
  }

**Comment by justkawal** [comment]
@tinhpt38 
Can you try latest version 

`excel: ^2.0.0-null-safety-3`

**Comment by tinhpt38** [comment]
@justkawal 
Thank you. It works very well.
