### ISSUE TITLE
How to get new excel file path

### ISSUE THREAD

**Issue by Invincible1996** [justkawal/excel#94]
I used  Excel.createExcel() to  create a new file,but I can't find it.

**Comment by justkawal** [comment]
@Invincible1996 
var excel = Excel.createExcel();

It will be available in the variable only.
You have to write the code or can have reference from the ReadMe of this library on How to save it into the external storage and also on how to save password protected excel file.

We don't write the file directly to your storage, as we are not having any storage permission as it's of no use to us.

By making this library independent of flutter frame-work, it provides us advantage to process and create excel files on dart-server easily.

**Comment by Invincible1996** [comment]
@justkawal Thanks! I got it.
