### ISSUE TITLE
Fuction Excel.decodeBytes(bytes) crashes my main thread

### ISSUE THREAD

**Issue by evega19** [justkawal/excel#96]
Hi, i tried to use the function Exce.decodeBytes like the example but to decode excel file interrump the progress indicator in the main screen. I tried using await but was the same issue.  I used the version 2.0.0-null-safety-3.

Future<Excel> decodifica( Uint8List bytes)async {
    return await Excel.decodeBytes(bytes);
 }

 Future<void>  excelRead(File file) async{
    var bytes = await file.readAsBytesSync();
    var excel = await decodifica(bytes);
    ...
}

Thank you for your helping.

**Comment by justkawal** [comment]
Please post the error log ?

**Comment by evega19** [comment]
There arent error log, only i cant see the progress indicator while the dependence is working, i suposed the issue its cause my Excel file has 10500 rows and 6 colummns. What do you think?

**Comment by justkawal** [comment]
I can't help you without looking at the logs, because the logs will tell that which part of code is causing issue, and more deeper insights

**Comment by gabrielchiquini** [comment]
maybe I have the same issue, I'm trying to use the same version and I get a error when decoding, this is my trace:
```
I/flutter ( 5354): Null check operator used on a null value
I/flutter ( 5354): #0      Parser._parseTable (package:excel/src/parser/parse.dart:422:9)
I/flutter ( 5354): #1      Parser._parseContent.<anonymous closure> (package:excel/src/parser/parse.dart:163:9)
I/flutter ( 5354): #2      Iterable.forEach (dart:core/iterable.dart:257:30)
I/flutter ( 5354): #3      Parser._parseContent (package:excel/src/parser/parse.dart:161:39)
I/flutter ( 5354): #4      Parser._startParsing (package:excel/src/parser/parse.dart:18:5)
I/flutter ( 5354): #5      new Excel._ (package:excel/src/excel.dart:74:12)
I/flutter ( 5354): #6      _newExcel (package:excel/src/excel.dart:17:20)
I/flutter ( 5354): #7      new Excel.decodeBytes (package:excel/src/excel.dart:84:12)
I/flutter ( 5354): #8      decode (package:stock_man/decoder/cei.dart:9:26)
I/flutter ( 5354): #9      OrderService.decodeFile (package:stock_man/service/order_service.dart:17:25)
I/flutter ( 5354): #10     OrderImport.build.<anonymous closure>.<anonymous closure> (package:stock_man/views/order_import.dart:25:28)
I/flutter ( 5354): <asynchronous suspension>
```

**Comment by gabrielchiquini** [comment]
I tried debugging the code to see if I can help. I found out that the line 420 is duplicating the `xl/` expression. In debugger I could see the `$target` variable has `/xl/worksheets/sheet1.xml` as value, which is a existing file, but after the interpolation, `findFile` method is called with `xl//xl/worksheets/sheet1.xml`

**Comment by alihabbash** [comment]
I also face the same issue
Excel.decodeBytes(bytes) is blocking the ui thread so, The progress indicator is freezed until the method is finished it's work

**Comment by hcaz** [comment]
This can be fixed by moving the `Excel.decodeBytes(_bytes)` call to another thread, flutter will handle this using isolates. 

The easiest and quickest way to do this is to make a top level function (Outside of any classes) that calls this package:
```dart
Excel parseExcelFile(List<int> _bytes) {
  return Excel.decodeBytes(_bytes);
}
```

Then you can call this using the `compute` flutter method like this:
```dart
Excel excel = await compute(parseExcelFile, _bytes);
```




A full example:
```dart
Excel parseExcelFile(List<int> _bytes) {
  return Excel.decodeBytes(_bytes);
}

class DataImport extends StatefulWidget {
  @override
  _DataImportState createState() => _DataImportState();
}

class _DataImportState extends State<DataImport> {
  void importFile() async {
    File file;
    try {
      FilePickerResult result =
          await FilePicker.platform.pickFiles(type: FileType.any);
      if (result != null) file = File(result.files.single.path);
    } catch (e) {}

    if (file != null) {
      Excel excel = await compute(parseExcelFile, _bytes);
      Sheet _dataSheet = excel.tables['Entries'];
      print('Loaded xlsx file successfully with ${_dataSheet.maxRows} rows');
    }
  }

  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Excel file import text'),
        centerTitle: true,
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Pick file'),
          onPressed: importFile,
        ),
      ),
    );
  }
}
```

@justkawal It may be worth including information about wrapping the plugin function calls in a `compute` for new users of the package.

**Comment by MalikSamiAwan** [comment]
@hcaz where is _bytes declared in example

**Comment by hcaz** [comment]
@MalikSamiAwan sorry, I missed the `file.readAsBytes()` from my example. I have updated the full example above to include it.

**Comment by MalikSamiAwan** [comment]
@hcaz Thanks for the quick response and help
but i am still facing this issue, i have xlsx file of around 468KB with 13 sheets and alot of data in it
can you please help me `outimport 'dart:io';

import 'package:excel/excel.dart';
import 'package:file_picker/file_picker.dart';
import 'package:film_finder/custom_widgets/custom_scaffold.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import '../custom_widgets/custom_buttons.dart';
import '../helpers/common_helper.dart';
import '../helpers/styles.dart';

Excel parseExcelFile(List<int> _bytes) {
  return Excel.decodeBytes(_bytes);
}

class TestingCodes extends StatefulWidget {
  const TestingCodes({Key? key}) : super(key: key);

  @override
  State<TestingCodes> createState() => _TestingCodesState();
}

class _TestingCodesState extends State<TestingCodes> {
  @override
  Widget build(BuildContext context) {
    return CustomScaffold(
      child: Container(
        child: Column(
          children: [
            CButton(
              color: greenButtonColor,
              borderRadius: 30,
              title: 'Upload Xlxs File',
              onClick: () async {
                String sheetToEdit = 'data';

                try {
                  var f = await FilePicker.platform.pickFiles(
                      allowMultiple: false,
                      allowedExtensions: ['xlsx'],
                      withData: true,
                      withReadStream: true,
                      type: FileType.custom,
                      allowCompression: false);
                  if (f != null && f.files.isNotEmpty) {
                    File file = new File(f.files.single.path!);
                    pprint(file.path, 1);
                    if (file != null) {
                      List<int> _bytes = await file.readAsBytes();
                      Excel excel = await compute(parseExcelFile, _bytes);
                      // Sheet? _dataSheet = excel.tables['data'];
                      // print(
                      //     'Loaded xlsx file successfully with ${_dataSheet!.maxRows} rows');
                      showSimpleDialog(
                          context: context,
                          title: 'Successfully!\nOrginal File Parsed');
                    }
                  }
                } catch (e) {
                  pprint(e.toString());
                  showNotification(context, e.toString());
                }
              },
              loading: true,
            ),
          ],
        ),
      ),
      heading: Center(
        child: Text.rich(TextSpan(children: [
          TextSpan(
            text: 'Import Data',
            style: subTitleTextStyle,
          ),
        ])),
      ),
    );
  }
}
`

**Comment by MalikSamiAwan** [comment]
Excel excel = await compute(parseExcelFile, _bytes);
gives 
**Null check operator used on a null value**
above error

**Comment by MalikSamiAwan** [comment]
@hcaz Thanks your solutions worked
Issue was that my xlsx file contains charts which were not getting computed so for i have delete that chart sheet
Let me know if there is any work around for that as well
Thanks again 
Saved my day

**Comment by MalikSamiAwan** [comment]
Is there any way we can open / Excel.decodeBytes file that contains chart in it

**Comment by justkawal** [comment]
I think it would be nice to post these questions on stackover flow as this is not related to an issue in `excel`.

If you're having another issue or the plugin throws error then feel free to re-open the issue again.

**Comment by Mahmoud3193** [comment]
> I also face the same issue Excel.decodeBytes(bytes) is blocking the ui thread so, The progress indicator is freezed until the method is finished it's work

How did this problem solved??

**Comment by FauconSpartiate** [comment]
@Mahmoud3193 With isolates, you can move the number crunching to a different thread, keeping the UI thread smooth.
https://github.com/justkawal/excel/issues/96#issuecomment-903656480
https://api.flutter.dev/flutter/foundation/compute.html?ref=blog.flutter.wtf
